"""Tests for app/utils/jurisdiction_enrich.py -- the shared "fill in a
missing state" module backed by real US Census Bureau Gazetteer/
relationship data (app/utils/jurisdiction_data/*.csv, generated by
scripts/build_jurisdiction_data.py). Every value asserted against here is
real, checked directly in the generated CSVs while building this module,
not synthetic.
"""

from app.utils import jurisdiction_enrich as je


def test_lookup_county_state_resolves_a_unique_name():
    assert je.lookup_county_state("Sonoma County") == "CA"
    assert je.lookup_county_state("Napa County") == "CA"


def test_lookup_county_state_normalizes_bare_and_prefixed_forms():
    # Bare name, "County of X", and the full "X County" form should all
    # key to the same real entry.
    assert je.lookup_county_state("Sonoma") == "CA"
    assert je.lookup_county_state("County of Sonoma") == "CA"
    assert je.lookup_county_state("sonoma county") == "CA"


def test_lookup_county_state_returns_none_for_a_real_collision():
    # Real, confirmed: "Washington County" exists in 30+ states -- must
    # not guess one.
    assert je.lookup_county_state("Washington County") is None


def test_lookup_county_state_returns_none_for_an_unknown_name():
    assert je.lookup_county_state("Not A Real County Zzyzx") is None


def test_lookup_city_state_resolves_a_unique_name():
    assert je.lookup_city_state("Chicago") == "IL"
    assert je.lookup_city_state("City of Chicago") == "IL"


def test_lookup_city_state_does_not_double_strip_a_name_that_legitimately_ends_in_city():
    # Real bug found and fixed 2026-08-12: "City of Oklahoma City" used to
    # lose its leading "City of " correctly, then *also* lose the
    # trailing "City" that's genuinely part of the real proper name --
    # landing on the wrong lookup key "Oklahoma", which collided with a
    # real, different place ("Oklahoma borough, PA") and silently
    # returned PA instead of OK. Real pattern, not a one-off: Carson
    # City, Jersey City, and Rapid City all have the same shape.
    assert je.lookup_city_state("City of Oklahoma City") == "OK"
    assert je.lookup_city_state("Oklahoma City") == "OK"


def test_lookup_city_state_resolves_real_consolidated_city_county_governments():
    # Real gap found and fixed 2026-08-15: build_jurisdiction_data.py's
    # build_places() only kept Census FUNCSTAT "A" (active incorporated
    # government) rows, silently dropping every real consolidated
    # city-county government -- Census codes these "B" (Baton Rouge,
    # Lafayette) or "F" ("... (balance)" statistical-area rows), not "A".
    # Confirmed against the real 2024 Gazetteer file (see
    # build_places()'s own comment for the full FUNCSTAT list). All 8 "F"
    # rows are asserted here, not just one -- this was a closed, verified
    # list at fix time, not a general pattern to trust blindly.
    assert je.lookup_city_state("Nashville-Davidson") == "TN"
    assert je.lookup_city_state("Indianapolis") == "IN"
    assert je.lookup_city_state("Louisville/Jefferson County") == "KY"
    assert je.lookup_city_state("Athens-Clarke County") == "GA"
    assert je.lookup_city_state("Augusta-Richmond County") == "GA"
    assert je.lookup_city_state("Butte-Silver Bow") == "MT"
    assert je.lookup_city_state("Baton Rouge") == "LA"


def test_lookup_city_state_does_not_over_strip_a_consolidated_government_name():
    # Real bug caught while fixing the gap above: naively applying the
    # normal trailing-type-word strip AFTER already stripping "unified
    # government (balance)" turned "Greeley County unified government
    # (balance)" into just "greeley" -- colliding with three unrelated
    # real cities named Greeley (CO, IA, KS) and making an otherwise-
    # unambiguous county lookup falsely ambiguous. "County" here is part
    # of the real name (a *county* consolidated government, distinct from
    # any city sharing the root name), same trap as Oklahoma City above.
    assert je.lookup_city_state("Greeley County") == "KS"
    # Plain "Greeley" must still correctly stay ambiguous -- this fix must
    # not accidentally make the collision worse in the other direction.
    assert je.lookup_city_state("Greeley") is None


def test_lookup_city_state_returns_none_for_real_collisions():
    # Real, confirmed: "Detroit" is a real city in MI, OR, AL, and TX;
    # "Charlotte" in NC, MI, IA, TX, and TN -- the exact real example this
    # module's design was built around (see lookup_by_domain() below for
    # how these two specific instances actually get resolved anyway).
    assert je.lookup_city_state("Detroit") is None
    assert je.lookup_city_state("Charlotte") is None


def test_lookup_city_state_returns_none_for_kansas_city():
    # A genuinely famous case, not just an obscure name collision --
    # Kansas City is a real, substantial, separately-incorporated city in
    # *both* Kansas and Missouri. Correctly stays unresolved either way.
    assert je.lookup_city_state("Kansas City") is None
    assert je.lookup_city_state("City of Kansas City") is None


def test_lookup_county_by_zip_resolves_a_real_zip():
    # Real Santa Rosa, CA ZIP, sitting inside Sonoma County.
    result = je.lookup_county_by_zip("95403")
    assert result == ("Sonoma County", "CA")


def test_lookup_county_by_zip_picks_the_larger_overlap_on_a_real_multi_county_zip():
    # Real ZCTA 94952 genuinely spans both Marin and Sonoma counties;
    # Marin's real overlap area is larger (confirmed in the generated
    # data: 264,775,970 vs 249,379,622) -- must pick Marin, not just the
    # first/alphabetically-first candidate.
    result = je.lookup_county_by_zip("94952")
    assert result == ("Marin County", "CA")


def test_lookup_county_by_zip_returns_none_for_a_non_zcta():
    assert je.lookup_county_by_zip("00000") is None


def test_lookup_place_by_zip_resolves_a_real_zip():
    result = je.lookup_place_by_zip("95403")
    assert result == ("Santa Rosa city", "CA")


def test_county_and_place_zip_lookups_can_legitimately_disagree():
    # The real trap this whole module is built around: 95403's county
    # answer (Sonoma County) and place answer (Santa Rosa city) are both
    # correct, but answer different questions -- a caller must pick
    # based on which TYPE it already knows this jurisdiction to be, never
    # let the city-shaped address silently stand in for the county.
    county = je.lookup_county_by_zip("95403")
    place = je.lookup_place_by_zip("95403")
    assert county[0] != place[0]
    assert county[1] == place[1] == "CA"  # same state either way


def test_find_zip_addresses_extracts_real_address_shape():
    # Real address confirmed live on a real PrimeGov page (Thousand
    # Oaks, CA) -- see tests/test_primegov.py's TOAKS_HEADER_HTML.
    text = "Andrew P. Fox City Council Chambers, 2100 E. Thousand Oaks Blvd., Thousand Oaks, CA 91362"
    assert je.find_zip_addresses(text) == [("Thousand Oaks", "CA", "91362")]


def test_find_zip_addresses_handles_zip_plus_four():
    text = "123 Main St, Sonoma, CA 95476-1234"
    assert je.find_zip_addresses(text) == [("Sonoma", "CA", "95476")]


def test_find_zip_addresses_returns_multiple_real_matches():
    text = "Main office: 1 Fiscal Dr, Santa Rosa, CA 95403. Branch: 123 Elm St, Napa, CA 94559."
    assert je.find_zip_addresses(text) == [
        ("Santa Rosa", "CA", "95403"),
        ("Napa", "CA", "94559"),
    ]


def test_find_zip_addresses_returns_empty_list_for_no_match():
    assert je.find_zip_addresses("No address here at all.") == []


def test_lookup_by_domain_resolves_a_confirmed_real_customer():
    known = je.lookup_by_domain("detroit-vod.cablecast.tv")
    assert known == je.KnownJurisdiction("Detroit", "city", "MI")


def test_lookup_by_domain_is_case_insensitive():
    assert je.lookup_by_domain("DETROIT-VOD.CABLECAST.TV").state == "MI"


def test_lookup_by_domain_returns_none_for_an_unconfirmed_domain():
    assert je.lookup_by_domain("some-random-city.example.com") is None


def test_resolve_state_prefers_a_confirmed_domain_over_an_ambiguous_name():
    # "Detroit" alone is unresolvable (real collision, see above) -- the
    # confirmed domain is what actually makes this resolve.
    assert (
        je.resolve_state("Detroit", "city", netloc="detroit-vod.cablecast.tv") == "MI"
    )


def test_resolve_state_falls_back_to_name_lookup_without_a_domain():
    assert je.resolve_state("Sonoma County", "county") == "CA"


def test_resolve_state_falls_back_to_zip_in_page_text_when_name_lookup_fails():
    # No confirmed domain, and the name itself ("Sonoma") isn't passed at
    # all here -- only a real address in the page text to go on, exactly
    # the "adapter found no state anywhere except a printed address" case
    # this module exists for.
    page_text = "Contact us: 575 Administration Dr, Santa Rosa, CA 95403"
    assert je.resolve_state(None, "county", page_text=page_text) == "CA"


def test_resolve_state_scopes_zip_lookup_to_the_caller_declared_type():
    # The real trap: a county-type caller must get the COUNTY crosswalk's
    # answer from a ZIP-in-text, not silently borrow the place crosswalk's
    # answer just because it's also a valid real place. Both answers give
    # the same real state here (CA), but the underlying lookup called
    # must be the county one -- verified indirectly via the "county" type
    # correctly still resolving at all for an address whose city portion
    # doesn't share Sonoma County's own name.
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    state = je.resolve_state("Sonoma", "county", page_text=page_text)
    assert state == "CA"


def test_resolve_state_returns_none_when_nothing_resolves():
    assert je.resolve_state("Not A Real Place Zzyzx", "city") is None
    assert je.resolve_state(None, "city") is None


def test_enrich_jurisdiction_text_appends_state_for_an_unambiguous_city():
    assert je.enrich_jurisdiction_text("City of Napa") == "City of Napa, CA"


def test_enrich_jurisdiction_text_detects_county_type_from_the_text_itself():
    assert je.enrich_jurisdiction_text("Sonoma County") == "Sonoma County, CA"


def test_enrich_jurisdiction_text_uses_a_confirmed_domain():
    assert (
        je.enrich_jurisdiction_text("Detroit", netloc="detroit-vod.cablecast.tv")
        == "Detroit, MI"
    )


def test_enrich_jurisdiction_text_falls_back_to_zip_in_page_text():
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    assert (
        je.enrich_jurisdiction_text("Sonoma County", page_text=page_text)
        == "Sonoma County, CA"
    )


def test_enrich_jurisdiction_text_leaves_ambiguous_names_unchanged():
    assert je.enrich_jurisdiction_text("City of Alexandria") == "City of Alexandria"


def test_enrich_jurisdiction_text_skips_falsy_values():
    assert je.enrich_jurisdiction_text(None) is None
    assert je.enrich_jurisdiction_text("") == ""


def test_enrich_jurisdiction_text_skips_a_value_that_already_has_a_comma():
    assert je.enrich_jurisdiction_text("League City, TX") == "League City, TX"


def test_enrich_jurisdiction_text_skips_a_callers_placeholder():
    assert (
        je.enrich_jurisdiction_text(
            "Unknown Jurisdiction", placeholder="Unknown Jurisdiction"
        )
        == "Unknown Jurisdiction"
    )


def test_enrich_jurisdiction_text_resolves_alexandria_via_confirmed_domain():
    # Confirmed live 2026-08-13: "Alexandria" alone stays ambiguous (see
    # test_enrich_jurisdiction_text_leaves_ambiguous_names_unchanged
    # above), but alexandria.granicus.com is a confirmed real customer.
    assert (
        je.enrich_jurisdiction_text(
            "City of Alexandria", netloc="alexandria.granicus.com"
        )
        == "City of Alexandria, VA"
    )


def test_known_jurisdiction_display_builds_full_string_for_a_confirmed_domain():
    assert (
        je.known_jurisdiction_display("slc.primegov.com")
        == "City of Salt Lake City, UT"
    )


def test_known_jurisdiction_display_is_case_insensitive():
    assert (
        je.known_jurisdiction_display("SLC.PRIMEGOV.COM")
        == "City of Salt Lake City, UT"
    )


def test_known_jurisdiction_display_returns_none_for_an_unconfirmed_domain():
    assert je.known_jurisdiction_display("some-random-city.example.com") is None


# --- finalize_jurisdiction() -- ingest-time validation/repair/split,
# built from the 2026-08-15 audit of all 649 real archived jurisdiction
# values. See JURISDICTION_METADATA_PLAN.md for the full design and
# BACKLOG.md's "Census-table baseline validation" entry for the data this
# was tuned against. Every case below is a real value pulled from that
# audit, not invented.


def test_finalize_jurisdiction_validates_a_clean_name_unchanged():
    result = je.finalize_jurisdiction("City of Sunnyvale, CA")
    assert result.jurisdiction == "City of Sunnyvale, CA"
    assert result.meeting_body is None
    assert result.confidence == "validated"


def test_table_lookup_recognizes_a_page_authored_abbreviation():
    # "Ft. Worth" is how real pages actually write it (user's own call,
    # 2026-08-15 -- see _STOPRULE_ABBREV_OK's comment); the Census table's
    # own key is the spelled-out "Fort Worth". Added specifically so
    # extract_jurisdiction_chain()'s validation gate (which requires a
    # candidate to actually validate before being accepted) doesn't
    # reject every abbreviated real name it was built to preserve.
    assert je._table_lookup("Ft. Worth") == ("place", ["TX"])
    assert je._table_lookup("Mt. Vernon") is not None
    assert je.finalize_jurisdiction("City of Ft. Worth").confidence == "validated"


def test_table_lookup_recognizes_a_spelled_out_saint():
    # Real bug found in the 2026-08-15 Census-baseline audit (BACKLOG.md):
    # stored "Saint Paul" used to miss the table's own key, since the
    # real Census places table stores this family abbreviated ("St. Paul
    # city", confirmed via a direct grep -- 148 real "St. " rows, zero
    # "Saint " rows), the opposite direction from "Ft. Worth"/"Mt.
    # Vernon" above, which the table stores spelled out.
    #
    # "AB" joined this list 2026-08-17 when the real Canadian data table
    # was added (BACKLOG.md's "Jurisdiction-bleed, confirmed cross-
    # platform" entry) -- St. Paul, Alberta is a real, confirmed Canadian
    # town, genuinely name-ambiguous with the 11 US states below now that
    # both live in the same table. Exactly the kind of real US/Canada
    # collision that entry predicted would "extend for free" from the
    # existing ambiguity-safety, not a bug in this fix.
    assert je._table_lookup("Saint Paul") == (
        "place",
        ["AB", "AK", "AR", "IA", "IN", "KS", "MN", "MO", "NE", "OR", "TX", "VA"],
    )
    assert je.finalize_jurisdiction("City of Saint Paul, MN").confidence == "validated"


def test_table_lookup_strips_a_hawaiian_okina():
    # Real bug found in the same audit: a real page can spell "Kauaʻi"
    # with the Hawaiian ʻokina, but the Census table's own key is plain
    # "kauai" (no diacritic).
    assert je._table_lookup("Kauaʻi County") == ("county", ["HI"])


def test_table_lookup_recognizes_a_township_county_subdivision():
    # WO-16 (BACKLOG.md, 2026-08-16): townships/county subdivisions
    # weren't in any table at all before this -- Upper Providence PA,
    # Greenburgh NY, and Upper Dublin PA are all confirmed real, live-
    # flagged as lookup misses in the 2026-08-15 Census-baseline audit.
    # Upper Providence Township genuinely exists twice in PA (Montgomery
    # and Delaware counties, both real, confirmed against the Census
    # gazetteer) -- still resolves unambiguously since both instances
    # agree on the state.
    assert je._table_lookup("Upper Providence Township") == ("subdivision", ["PA"])
    assert je._table_lookup("Greenburgh") == ("subdivision", ["NY"])
    assert (
        je.finalize_jurisdiction("Township of Upper Dublin").confidence == "validated"
    )
    assert je.finalize_jurisdiction("Greenburgh, NY").confidence == "validated"


def test_finalize_jurisdiction_repairs_trailing_bleed():
    # Real value, Hercules CA's Granicus page -- the still-open
    # granicus.py body-regex bug (BACKLOG.md) let agenda-heading text run
    # on past the real city name. State gets filled in on the now-clean
    # name too (_fill_missing_state(), added 2026-08-15 running the
    # workstream-4 backfill dry run): the ORIGINAL bled string could
    # never resolve a state (it doesn't validate), so nothing upstream
    # ever got the chance to look one up until now.
    result = je.finalize_jurisdiction(
        "City of Hercules. XIV. PUBLIC COMMUNICATIONS XV.",
        netloc="hercules.granicus.com",
    )
    assert result.jurisdiction == "City of Hercules, CA"
    assert result.meeting_body is None
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_fills_missing_state_when_base_name_already_validates():
    # Real bug, found 2026-08-21 (BACKLOG.md's "16 real pairs of a
    # jurisdiction appearing twice" entry): a bare name that already
    # validates against the place/county table (even ambiguously, e.g.
    # "Albany" matches 14 different real states) used to be returned
    # completely unchanged, since only the `_trim_repair()`/
    # `_split_entity_prefix()` branches called `_fill_missing_state()` --
    # this fast "validated" path never did. Confirmed live: the exact
    # same real customer domain (`dublin.granicus.com`) produced both a
    # correctly state-suffixed "Dublin, CA" page and a permanently bare
    # "Dublin" page, purely because one extraction happened to find a
    # comma-state in the raw text and the other didn't.
    #
    # No netloc -> stays ambiguous, no guess (same safety
    # `_fill_missing_state()`/`resolve_state()` already guarantee
    # elsewhere -- "Albany" alone is genuinely ambiguous nationally).
    result = je.finalize_jurisdiction("Albany", netloc=None)
    assert result.jurisdiction == "Albany"
    assert result.confidence == "validated"

    # A netloc that resolves unambiguously via the domain registry DOES
    # now get the state filled in -- this is the real fix.
    result = je.finalize_jurisdiction("Dublin", netloc="dublin.granicus.com")
    assert result.jurisdiction == "Dublin, CA"
    assert result.confidence == "validated"

    # Already has a state suffix -- unaffected, same as before (this
    # fast path's other branch never called `_fill_missing_state()` and
    # still doesn't).
    result = je.finalize_jurisdiction("Dublin, OH", netloc="dublin.granicus.com")
    assert result.jurisdiction == "Dublin, OH"
    assert result.confidence == "validated"


def test_finalize_jurisdiction_domain_registry_resolves_distinct_same_name_counties():
    # Real finding from the same 2026-08-21 investigation: several of the
    # 16 "duplicate" pairs turned out NOT to be duplicates at all -- the
    # bare row was a genuinely different, unrelated real jurisdiction
    # that happened to share an ambiguous name with an already-archived
    # suffixed one. Confirmed live via each domain's own real page
    # content/customer slug (see jurisdiction_enrich.py's registry
    # comments for the specific evidence): Washington County's own page
    # literally renders `<div id="mottotext">Oregon</div>`, not Virginia;
    # Cook County's customer slug is "cocookmn" (Minnesota), not
    # Illinois; Frederick County's is "fcva" (Virginia), not Maryland;
    # Glendale's is "glendale-az" (Arizona), not California.
    assert (
        je.finalize_jurisdiction(
            "Washington County", netloc="washingtoncounty.civicweb.net"
        ).jurisdiction
        == "Washington County, OR"
    )
    assert (
        je.finalize_jurisdiction(
            "Cook County", netloc="cocookmn.civicweb.net"
        ).jurisdiction
        == "Cook County, MN"
    )
    assert (
        je.finalize_jurisdiction(
            "Frederick County", netloc="fcva.granicus.com"
        ).jurisdiction
        == "Frederick County, VA"
    )
    assert (
        je.finalize_jurisdiction(
            "Glendale", netloc="glendale-az.granicus.com"
        ).jurisdiction
        == "Glendale, AZ"
    )


def test_finalize_jurisdiction_preserves_state_suffix_through_a_repair():
    result = je.finalize_jurisdiction(
        "City of Boston to accept and expend the amount of, MA"
    )
    assert result.jurisdiction == "City of Boston, MA"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_fills_a_state_the_bled_original_never_could():
    # Real gap found live 2026-08-15 running the workstream-4 backfill dry
    # run: "City of Castle Pines History of Parks and Recreat" never
    # validates, so the ORIGINAL adapter-time state-enrichment attempt
    # correctly found nothing (a bled name can't be looked up). Once
    # repaired down to "Castle Pines" -- a real, unambiguous CO city --
    # this function gets one more shot at resolving a state, rather than
    # leaving the repaired name state-less forever just because the first
    # attempt (on the wrong, bled text) failed.
    result = je.finalize_jurisdiction(
        "City of Castle Pines History of Parks and Recreat"
    )
    assert result.jurisdiction == "City of Castle Pines, CO"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_never_trims_a_legitimately_long_real_name():
    # Real value, a real Bay Area agency -- trimming from the right would
    # eventually hit "Bay" (a real place), but nothing in the discarded
    # tail looks like bleed, so this must be left whole.
    result = je.finalize_jurisdiction("Bay Area Headquarters Authority")
    assert result.jurisdiction == "Bay Area Headquarters Authority"
    assert result.meeting_body is None
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_splits_a_real_entity_prefix():
    # Real value, hacsc.granicus.com -- "Housing Authority" is a real,
    # distinct governing body, not bleed; splitting it out (rather than
    # discarding it, or leaving the whole string un-validatable) is the
    # correct outcome per JURISDICTION_METADATA_PLAN.md's design. State
    # gets filled in on the split-out jurisdiction half too
    # (_fill_missing_state(), 2026-08-15) -- "Santa Clara" alone would be
    # ambiguous, but "County of Santa Clara" resolves unambiguously.
    result = je.finalize_jurisdiction("Housing Authority of the County of Santa Clara")
    assert result.jurisdiction == "County of Santa Clara, CA"
    assert result.meeting_body == "Housing Authority"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_does_not_split_off_a_bare_type_phrase():
    # Real bug caught testing this fix against all 649 archived rows:
    # "The City of Memphis" and "City and County of Denver" both look
    # like the entity-split shape, but "The City"/"City and County" are
    # not real distinct entities, just the ordinary jurisdiction-type
    # phrasing -- splitting them off would produce meaningless bodies.
    result = je.finalize_jurisdiction("The City of Memphis, TN")
    assert result.meeting_body is None
    assert result.jurisdiction == "The City of Memphis, TN"

    result = je.finalize_jurisdiction("City and County of San Francisco")
    assert result.meeting_body is None
    assert result.jurisdiction == "City and County of San Francisco"


def test_finalize_jurisdiction_authoritative_domain_overrides_even_a_plausible_extraction():
    # The real Holladay bug this design exists to close: PrimeGov's own
    # text extraction on slc.primegov.com sometimes finds a genuine,
    # table-valid *wrong* city ("City of Holladay, UT" -- Holladay is a
    # real Utah city) instead of the real header. Table validation alone
    # can never catch a plausible-but-wrong value; only an authoritative
    # domain override can.
    result = je.finalize_jurisdiction("City of Holladay, UT", netloc="slc.primegov.com")
    assert result.jurisdiction == "Salt Lake City, UT"
    assert result.confidence == "authoritative"


def test_finalize_jurisdiction_authoritative_domain_fills_a_blank_too():
    result = je.finalize_jurisdiction(None, netloc="slc.primegov.com")
    assert result.jurisdiction == "Salt Lake City, UT"
    assert result.confidence == "authoritative"


def test_finalize_jurisdiction_fallback_domain_fires_on_blank_or_unvalidated_extraction():
    # A "fallback"-strength entry fires whenever extraction leaves nothing
    # usable -- blank, or present but not table-valid -- unlike
    # "authoritative", which overrides even a plausible-looking real
    # extraction (see the Holladay test above). This is deliberately
    # different from "only when blank": alexandria.granicus.com is
    # registered because this single-tenant customer is confirmed to
    # always be Alexandria, VA, so an unvalidatable extraction on this
    # specific host is still safer to answer from the registry than to
    # leave unverified.
    result = je.finalize_jurisdiction(None, netloc="alexandria.granicus.com")
    assert result.jurisdiction == "Alexandria, VA"
    assert result.confidence == "fallback"

    result = je.finalize_jurisdiction(
        "Not A Real Place Zzyzx", netloc="alexandria.granicus.com"
    )
    assert result.jurisdiction == "Alexandria, VA"
    assert result.confidence == "fallback"


def test_finalize_jurisdiction_does_not_consult_an_unregistered_domain():
    result = je.finalize_jurisdiction(
        "Some Unvalidatable Text", netloc="totally-unknown-host.example.com"
    )
    assert result.jurisdiction == "Some Unvalidatable Text"
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_returns_blank_confidence_for_nothing_at_all():
    result = je.finalize_jurisdiction(None)
    assert result.jurisdiction is None
    assert result.confidence == "blank"


# --- extract_jurisdiction_chain() (2026-08-15, workstream 2 promotions) ---
# Shared fallback chain for adapters with no bespoke extraction (Swagit,
# generic_fallback) -- see the module-level comment above
# extract_jurisdiction_chain() in jurisdiction_enrich.py for the tournament
# results these three tiers are promoted from.


def test_extract_jurisdiction_chain_stoprule_repairs_a_real_bleed_case():
    # The real Hercules bleed confirmed live 2026-08-15 (see BACKLOG.md's
    # "Granicus jurisdiction bleed" entry): the shipped body regex has no
    # sentence boundary and runs straight into an agenda's roman-numeral
    # list. The stop rule fixes this at the source, before the enricher's
    # own repair machinery would even need to run.
    page_text = "Welcome. Meeting of the City of Hercules. XIV. PUBLIC COMMUNICATIONS XV. ADJOURNMENT"
    result = je.extract_jurisdiction_chain(
        page_text=page_text,
        html=f"<html>{page_text}</html>",
        url="https://hercules.granicus.com/player/clip/1306",
    )
    assert result == "City of Hercules, CA"


def test_extract_jurisdiction_chain_stoprule_keeps_a_real_abbreviation():
    page_text = "Agenda for the City of Ft. Worth regular council session"
    result = je.extract_jurisdiction_chain(
        page_text=page_text, html="", url="https://example.granicus.com/clip/1"
    )
    assert result == "City of Ft. Worth"


def test_extract_jurisdiction_chain_falls_back_to_capitalization_walk():
    # No "City/County/Town of" trigger for the stop rule to find in plain
    # text, but the tag-bounded walk (mirrors PrimeGov's own shipped
    # regex) finds it in the raw markup.
    # ("Oklahoma City" is nationally unambiguous, so
    # enrich_jurisdiction_text() correctly appends its real state too.)
    html = "<table><td>OKLAHOMA CITY</td><td>FORMAL AGENDA</td></table> City of Oklahoma City<br>more"
    result = je.extract_jurisdiction_chain(
        page_text="no trigger here", html=html, url="https://example.com/clip/1"
    )
    assert result == "City of Oklahoma City, OK"


def test_extract_jurisdiction_chain_falls_back_to_validated_subdomain():
    # Real case this tier exists for: wordninja over-splits "galesburg"
    # into "Gales Burg" (a real, confirmed bug this session, not
    # hypothetical -- see BACKLOG.md), which never validates. Checking the
    # raw unsplit label first fixes it without needing wordninja at all.
    result = je.extract_jurisdiction_chain(
        page_text="no trigger",
        html="<html>no trigger</html>",
        url="https://galesburg.granicus.com/player/clip/1",
    )
    assert result == "Galesburg"


def test_extract_jurisdiction_chain_subdomain_resolves_state_via_registry():
    # sandiego.granicus.com is a real, already-registered known domain --
    # confirms the subdomain tier's candidate is run through
    # enrich_jurisdiction_text() (which consults the registry), not
    # returned bare, since "San Diego" alone is nationally ambiguous
    # (CA and TX both have a real "San Diego").
    result = je.extract_jurisdiction_chain(
        page_text="no trigger",
        html="<html>no trigger</html>",
        url="https://sandiego.granicus.com/player/clip/1",
    )
    assert result == "San Diego, CA"


def test_extract_jurisdiction_chain_rejects_a_capitalization_walk_false_positive():
    # Real, confirmed-live bug (2026-08-15, found while dry-running the
    # workstream 4 backfill against real cached HTML, not hypothetical):
    # a Broward MPO Swagit page (browardmpo.new.swagit.com/videos/359517)
    # has an ALL-CAPS caption line of spoken testimony -- "...IN THE CITY
    # OF FORT LAUDERDALE THAT'S IDENTIFIED..." -- that the capitalization
    # walk matched into, producing "City of Fort Lauderdale That'S
    # Identified." That candidate doesn't validate (nor trim-repair,
    # since "That'S"/"Identified" show no bleed signal -- both are
    # capitalized, so _looks_like_bleed() correctly refuses to guess
    # which prefix is real) and must be discarded, not stored -- a real
    # city mention inside spoken dialogue is not evidence of the
    # meeting's own jurisdiction.
    page_text = (
        "ALSO, THE S. MIDDLE RIVER MOBILITY PROJECT IN THE CITY OF FORT LAUDERDALE THAT'S "
        "IDENTIFIED. Next item on the agenda."
    )
    html = f"<html><body><p>{page_text}</p></body></html>"
    result = je.extract_jurisdiction_chain(
        page_text="no trigger for the stop rule here",
        html=html,
        url="https://browardmpo.new.swagit.com/videos/1",
    )
    assert result is None


def test_extract_jurisdiction_chain_declines_rather_than_guesses():
    # No trigger phrase, no tag-bounded match, and a subdomain that
    # doesn't validate against any real place/county -- every tier
    # declines, so the chain returns None rather than fabricating
    # something.
    result = je.extract_jurisdiction_chain(
        page_text="nothing useful here",
        html="<html>nothing useful here</html>",
        url="https://totallymadeupgarbage999.example.com/clip/1",
    )
    assert result is None


# --- Canadian data + Title-Case/ALL-CAPS bleed fix (2026-08-17,
# BACKLOG.md's "Jurisdiction-bleed, confirmed cross-platform" entry) ---
# Every raw string below is real, taken verbatim from that entry's
# confirmed-live table (source URLs there), not invented -- same
# "synthetic only for a narrower edge case, real facts always" convention
# as the rest of this suite.


def test_lookup_city_state_resolves_real_canadian_cities():
    # scripts/build_jurisdiction_data.py's build_canada_places() merges
    # real Statistics Canada Standard Geographical Classification (SGC)
    # 2021 census-subdivision rows into the SAME places.csv the US data
    # already lives in -- confirmed by reading _load_name_state_table()
    # directly that it's fully data-agnostic, no code change needed
    # there. 5,028 real Canadian rows added this way (see build script's
    # own output/comment).
    assert je.lookup_city_state("Guelph") == "ON"
    assert je.lookup_city_state("Thunder Bay") == "ON"
    assert je.lookup_city_state("Lethbridge") == "AB"
    assert je.lookup_city_state("Kelowna") == "BC"
    assert je.lookup_city_state("New Westminster") == "BC"
    assert je.lookup_city_state("Oshawa") == "ON"
    assert je.lookup_city_state("Mississauga") == "ON"


def test_lookup_city_state_delta_stays_ambiguous_across_countries():
    # Real, confirmed collision the merge makes possible: "Delta" is a
    # real BC city AND a real US place (Delta, CO/IA/MO/UT and more) --
    # the existing ambiguity-safety (only resolve a bare name when it
    # maps to exactly one state) extends for free to a genuine US/Canada
    # collision once both live in the same table, per BACKLOG.md -- no
    # new ambiguity-handling code was needed for this.
    assert je.lookup_city_state("Delta") is None


def test_finalize_jurisdiction_repairs_real_canadian_bleed_cases():
    # Real raw values, all confirmed live on *.escribemeetings.com --
    # BACKLOG.md's "Jurisdiction-bleed, confirmed cross-platform" entry.
    # Before the Canadian data table existed, none of these validated
    # against any table at all, so `_trim_repair()` never even got to
    # call `_looks_like_bleed()` -- they fell straight through to
    # "unverified" unchanged, the same bucket a real correct Canadian
    # name lands in, since the system couldn't tell the two apart.
    result = je.finalize_jurisdiction(
        "Mississauga as being part of the Treaty and Traditional Territory "
        "of the Mississaugas of the Credit First Nation"
    )
    assert result.jurisdiction == "Mississauga, ON"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Oshawa is situated on lands within the traditional and treaty "
        "territory of the Michi Saagiig and Chippewa Anishinaabeg and the "
        "signatories of the Williams Treaties"
    )
    assert result.jurisdiction == "Oshawa, ON"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "New Westminster. Recommendation THAT the goal of zero traffic "
        "fatalities and serious injuries"
    )
    assert result.jurisdiction == "New Westminster, BC"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Guelph now hold a meeting that is closed to the public"
    )
    assert result.jurisdiction == "Guelph, ON"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Thunder Bay be approved in accordance with Table"
    )
    assert result.jurisdiction == "Thunder Bay, ON"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Lethbridge currently utilizes Standing Policy Committees"
    )
    assert result.jurisdiction == "Lethbridge, AB"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_peterborough_resolves_with_the_real_data_added_tonight():
    # The one case BACKLOG.md flagged as unexplained -- re-checked
    # directly against the real (if BACKLOG.md-truncated) raw string, not
    # guessed. Turns out this one already repaired (state-less) even
    # BEFORE tonight's fixes: "Peterborough" happens to already collide
    # with a real US place, Peterborough town NH -- but only in the
    # county-*subdivision* table (New England towns are often COUSUB, not
    # an incorporated Census "place"), which `_table_lookup()` (used for
    # trim validation) checks but `lookup_city_state()` (used for
    # state-filling) does not. So this session could not reproduce
    # BACKLOG.md's "still not trimmed" claim against current code --
    # most likely explanation is the already-archived page's stored
    # value simply predates whatever earlier fix made this validate, and
    # was never reprocessed (reprocessing already-archived pages is out
    # of scope here, same as this session's other data-quality fixes).
    # What tonight's Canadian-data fix specifically adds: an actual
    # province now resolves too, since "Peterborough" is a real ON place
    # unambiguously once it's the only *place*-table (not
    # subdivision-table) entry -- the NH collision lives in a table
    # lookup_city_state() never consults, so it doesn't block this.
    raw = (
        "Peterborough is committed to making meetings accessible for "
        "people of all abilities"
    )
    result = je.finalize_jurisdiction(
        raw, netloc="pub-peterborough.escribemeetings.com"
    )
    assert result.jurisdiction == "Peterborough, ON"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_repairs_title_case_bleed_with_no_lowercase_signal():
    # Real raw values -- the Title-Case/ALL-CAPS blind spot BACKLOG.md
    # flagged as a residual gap from an earlier fix: every word in the
    # discarded tail starts uppercase (no lowercase-initial word, no
    # digit, no roman numeral), so the pre-2026-08-17 signals all missed
    # these. _MIN_BLEED_WORD_RUN's own comment in jurisdiction_enrich.py
    # has the full calibration evidence for the threshold.
    result = je.finalize_jurisdiction(
        "Sarasota Legacy Business PLEDGE OF PUBLIC", netloc="sarasota.granicus.com"
    )
    assert result.jurisdiction == "Sarasota, FL"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Hollywood Be Awarded As A Subrecipient O", netloc="hollywoodfl.granicus.com"
    )
    assert (
        result.jurisdiction == "Hollywood"
    )  # ambiguous (FL/AL/SC) -- no guessed state
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Hampton Zoning Ordinance Regarding Standa", netloc="hampton.granicus.com"
    )
    assert result.jurisdiction == "Hampton"  # ambiguous across many states -- no guess
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Kelowna Regular Council Meeting AGENDA Monday",
        netloc="kelownapublishing.escribemeetings.com",
    )
    assert result.jurisdiction == "Kelowna, BC"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Delta Housing Accelerator Fund Initiatives Summary.pdf Recommendation",
        netloc="pub-delta.escribemeetings.com",
    )
    assert result.jurisdiction == "Delta"  # ambiguous, real BC city AND real US places
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_title_case_fix_does_not_over_trigger_on_real_long_names():
    # Real, confirmed-long entity names BACKLOG.md names explicitly as
    # must-not-trim. Three ("Lake Washington School District", "Bay Area
    # Headquarters Authority", "Capital Metropolitan Transportation
    # Authority") have a shortest validating prefix ("Lake"/"Bay"/
    # "Capital") whose discarded tail is exactly 3 words -- one word
    # short of _MIN_BLEED_WORD_RUN, which is exactly the real boundary
    # that constant was picked against, not a coincidence. The fourth
    # ("Lexington-Fayette Urban County Government") trims to a different
    # valid prefix ("Lexington-Fayette Urban", matching the Census
    # table's own "Lexington-Fayette urban county" key) with a 1-word
    # tail ("Government") -- also below the threshold, so it's left
    # whole too, same outcome via a different cut point.
    for name in (
        "Capital Metropolitan Transportation Authority",
        "Lake Washington School District",
        "Bay Area Headquarters Authority",
        "Lexington-Fayette Urban County Government",
    ):
        result = je.finalize_jurisdiction(name)
        assert result.jurisdiction == name
        assert result.confidence == "unverified"


def test_extract_jurisdiction_chain_still_rejects_the_broward_false_positive():
    # Real regression guard for the word-run fix specifically: "That'S
    # Identified" is only 2 words, below _MIN_BLEED_WORD_RUN -- confirms
    # the new signal doesn't accidentally start accepting the exact false
    # positive
    # test_extract_jurisdiction_chain_rejects_a_capitalization_walk_false_positive()
    # above was built to reject.
    page_text = (
        "ALSO, THE S. MIDDLE RIVER MOBILITY PROJECT IN THE CITY OF FORT LAUDERDALE THAT'S "
        "IDENTIFIED. Next item on the agenda."
    )
    html = f"<html><body><p>{page_text}</p></body></html>"
    result = je.extract_jurisdiction_chain(
        page_text="no trigger for the stop rule here",
        html=html,
        url="https://browardmpo.new.swagit.com/videos/1",
    )
    assert result is None


def test_finalize_jurisdiction_single_word_bleed_tails_remain_a_known_residual_gap():
    # "Town of Castle Rock Authorizing": still an open gap, 2026-08-18.
    # Its discarded tail is only 1 word ("Authorizing"), below
    # _MIN_BLEED_WORD_RUN, and "authorizing" isn't on the closed
    # `_KNOWN_JUNK_TAIL_WORDS` stoplist (2026-08-18 fix #4) since no real
    # confirmed-live example has grounded it there yet -- there isn't
    # enough signal in a single capitalized word to tell real bleed apart
    # from a legitimate short suffix without risking exactly the
    # over-trim
    # test_finalize_jurisdiction_title_case_fix_does_not_over_trigger_on_real_long_names()
    # above guards against, so it's documented honestly as an open gap in
    # BACKLOG.md rather than silently left.
    result = je.finalize_jurisdiction("Town of Castle Rock Authorizing")
    assert result.jurisdiction == "Town of Castle Rock Authorizing"
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_known_junk_tail_words_are_repaired():
    # Real, confirmed-live raw values (2026-08-18, found live on
    # /coverage) that fix #4's closed `_KNOWN_JUNK_TAIL_WORDS` stoplist
    # newly repairs -- their discarded tail is only 1 word ("Meeting",
    # "Attachments"), below _MIN_BLEED_WORD_RUN, but both words are
    # grounded in a real confirmed example so the stoplist authorizes the
    # trim anyway (see that constant's own docstring for why this is safe
    # where a general short-tail rule wouldn't be).
    result = je.finalize_jurisdiction(
        "Brampton Meeting", netloc="pub-brampton.escribemeetings.com"
    )
    assert result.jurisdiction == "Brampton, ON"
    assert result.confidence == "repaired"

    result = je.finalize_jurisdiction(
        "Peterborough Attachments", netloc="pub-peterborough.escribemeetings.com"
    )
    assert result.jurisdiction == "Peterborough, ON"
    assert result.confidence == "repaired"


# --- Second-pass fixes, 2026-08-17: `_trim_repair()` no longer falls
# through past a literal-matching prefix, a real consolidated-government
# formatting gap, and a positive-evidence entity-type-suffix allowlist
# (see jurisdiction_enrich.py's own comments on `_trim_repair()`,
# `_QUERY_GOVERNMENT_TYPE_RE`, and `_ENTITY_TYPE_SUFFIX_WORDS` for the
# full reasoning). All real, confirmed via the production
# GET /internal/jurisdiction/bleed-backfill-candidates audit, not
# invented -- see BACKLOG.md's "Jurisdiction-bleed, confirmed
# cross-platform" entry.


def test_trim_repair_does_not_fall_through_past_a_literal_match_richmond_hill():
    # Real false positive introduced by the first bleed-signal fix: the
    # old "keep scanning shorter cuts" behavior correctly rejected the
    # longest valid prefix "Richmond Hill" (a real, different place;
    # tail "Single Source Award" is only 3 words, not bleed) but then
    # kept going to the shorter "Richmond" (tail "Hill Single Source
    # Award" is 4 words -> looked like bleed) and wrongly repaired to
    # "Richmond" -- destroying "Richmond Hill". Must now stay whole.
    result = je.finalize_jurisdiction("Richmond Hill Single Source Award")
    assert result.jurisdiction == "Richmond Hill Single Source Award"
    assert result.confidence == "unverified"


def test_trim_repair_does_not_fall_through_past_a_literal_match_east_bay():
    # Same shape as Richmond Hill above: "East Bay" (real place, tail
    # "Regional Park District" not bleed) used to be skipped past in
    # favor of the shorter "East" (a real OH township), mangling a real,
    # legitimately-long agency name.
    result = je.finalize_jurisdiction("East Bay Regional Park District, CA")
    assert result.jurisdiction == "East Bay Regional Park District, CA"
    assert result.confidence == "unverified"


def test_trim_repair_still_finds_a_shorter_repair_past_a_heuristic_only_match():
    # The literal-vs-heuristic distinction the two fixes above rely on
    # must not become too conservative: "East Providence City" only
    # "validates" via the secondary trailing-"City"-stripped candidate
    # "East Providence" (the literal text "east providence city" isn't a
    # real table key -- "City" here is really the start of "City
    # Council" in the surrounding text, not part of the entity name), so
    # its non-bleed 3-word tail must NOT stop the search the way a
    # literal match would. Scanning should continue to the shorter,
    # literal match "East Providence" (tail "City Council Live Stream",
    # 4 words -> bleed), and repair to that.
    result = je.finalize_jurisdiction("East Providence City Council Live Stream")
    assert result.jurisdiction == "East Providence, RI"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_resolves_a_real_consolidated_government_page_spelling():
    # Real raw jurisdiction text from an already-archived page: "Metro"
    # (bare, no "Government") and spaces around the slash, neither of
    # which the stored Census key ("louisville/jefferson county",
    # produced from "Louisville/Jefferson County metro government
    # (balance)") matched before this fix. Must resolve as a validated
    # consolidated-government name, not get destructively trimmed to a
    # bare, nationally-ambiguous "Louisville".
    result = je.finalize_jurisdiction("Louisville / Jefferson County Metro")
    assert result.jurisdiction == "Louisville / Jefferson County Metro"
    assert result.confidence == "validated"

    # Control case: Nashville-Davidson's own real archived spelling
    # already matched before this fix (it strips down to "nashville-
    # davidson" via the ordinary trailing-"County"-word strip, no slash
    # or bare-"Metro" involved) -- confirms the new consolidated-
    # government candidate tier doesn't change already-correct behavior.
    result = je.finalize_jurisdiction("Nashville-Davidson County, TN")
    assert result.jurisdiction == "Nashville-Davidson County, TN"
    assert result.confidence == "validated"


def test_finalize_jurisdiction_protects_a_real_special_district_entity_suffix():
    # Real, confirmed residual gap as of the first bleed-signal fix: the
    # longest real prefix ("St. Johns", a real place) has a tail ("River
    # Water Management District") that's already 4 Title-Case words --
    # indistinguishable BY SHAPE ALONE from real bleed like "Legacy
    # Business PLEDGE OF PUBLIC". The entity-type-suffix allowlist adds
    # positive evidence (the tail ends in a real government-entity-type
    # word, "District") so this now correctly stays whole instead of
    # being destructively trimmed to "St. Johns, FL" (losing the real
    # water-management-district identity).
    result = je.finalize_jurisdiction("St. Johns River Water Management District, FL")
    assert result.jurisdiction == "St. Johns River Water Management District, FL"
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_protects_a_real_water_utility_authority():
    # Found while verifying the fix above, not explicitly reported: this
    # real agency name (already cited in BACKLOG_DONE.md's audit as a
    # "real, correct, legitimately-long agency name") was ALSO being
    # wrongly trimmed to "Albuquerque, NM" by the shipped word-run-only
    # signal -- confirmed via the real bleed-backfill-candidates audit,
    # not previously covered by any test. "Albuquerque" is the only
    # valid prefix (literal match), and its tail "Bernalillo County
    # Water Utility Authority" (5 words) ends in "Authority" -- now
    # protected.
    result = je.finalize_jurisdiction(
        "Albuquerque Bernalillo County Water Utility Authority"
    )
    assert (
        result.jurisdiction == "Albuquerque Bernalillo County Water Utility Authority"
    )
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_entity_suffix_allowlist_does_not_protect_real_bleed():
    # The entity-type-suffix allowlist is end-anchored, not "contains" --
    # real bleed can legitimately contain one of the protected words
    # (e.g. "Committee") without actually ENDING in a protected word or
    # phrase. Kenora's real, already-correct repair must keep working:
    # its tail "Committee of the Whole Agenda Thursday" contains
    # "Committee" but ends in "Agenda Thursday", which isn't protected
    # (and also independently trips the plain lowercase-word bleed
    # signal via "of"/"the").
    result = je.finalize_jurisdiction("Kenora Committee of the Whole Agenda Thursday")
    assert result.jurisdiction == "Kenora, ON"
    assert result.confidence == "repaired"

    # Guelph's real "Committee of Adjustment" bleed case, same shape --
    # both cases are already caught by the lowercase-word signal (the
    # "of" in each tail) before the entity-suffix allowlist is even
    # consulted, but asserted directly here since both phrases are also
    # explicitly listed in `_ENTITY_TYPE_SUFFIX_PHRASES` for the ALL-CAPS
    # case (not yet observed live) -- this confirms the mixed-case
    # spelling these were actually found in still repairs correctly.
    result = je.finalize_jurisdiction("Guelph Committee of Adjustment")
    assert result.jurisdiction == "Guelph, ON"
    assert result.confidence == "repaired"


def test_ends_with_known_entity_suffix_is_end_anchored_not_contains():
    # Direct unit test of the helper itself: a protected word appearing
    # mid-tail (not at the end) must not count -- this is the exact
    # distinction that keeps Kenora's real bleed case (above) from being
    # wrongly protected just because "Committee" appears somewhere in
    # the discarded text.
    assert je._ends_with_known_entity_suffix("Water Management District") is True
    assert je._ends_with_known_entity_suffix("District Meeting Agenda") is False
    assert je._ends_with_known_entity_suffix("Committee of the Whole") is True
    assert (
        je._ends_with_known_entity_suffix("Committee of the Whole Agenda Thursday")
        is False
    )


# --- Jurisdiction misattribution, confirmed 2026-08-19 (BACKLOG.md's
# "Jurisdiction misattribution" entry) -- 4 real instances found via
# incidental spot-checking, all real, verifiable places even where the
# exact originating URL could not be recovered this session. Root-caused
# to TWO separate bugs, not one, verified by tracing the actual code path
# each case would hit (not assumed from the failure shape alone, per the
# investigation's own explicit ask):
#
# 1. `_trim_repair()`'s `_looks_like_bleed()` treated a discarded tail
#    starting with "of" as proof of agenda-prose bleed -- but "of" is the
#    one structural connector this whole module's OTHER mechanisms already
#    treat as real jurisdiction-naming syntax, not prose. Explains
#    Douglas, MI (see below); does NOT explain Courtenay/Burlington or
#    Victorville/San Bernardino County, which have zero token overlap
#    with their wrong values -- no trim of a single string can turn
#    "Courtenay" into "Burlington".
# 2. `extract_jurisdiction_chain()`'s stoprule/capitalization-walk tiers
#    accept the FIRST "City/County/Town of X" match anywhere in page
#    text/HTML, with no check that it's the page's OWN identity rather
#    than an unrelated mention elsewhere (a correspondence item, a
#    cross-jurisdictional reference, boilerplate). The existing "must
#    validate" gate (built for the Broward MPO/Fort Lauderdale case,
#    tested above) only catches outright-garbage candidates, not a clean,
#    validating WRONG place. Explains Courtenay/Burlington and
#    Victorville/San Bernardino County.
#
# Tulare County/Visalia (the 4th backlog case) could not be confirmed
# fixed this session -- see the honest residual-gap test at the bottom of
# this section for why.


def test_finalize_jurisdiction_repairs_douglas_mi_not_the_village_ok():
    # Root cause #1, `_looks_like_bleed()`'s "of" fix. Douglas, MI is a
    # real Michigan VILLAGE (not a City -- confirmed, Allegan County), so
    # a page carrying its real, correct self-branding "The Village of
    # Douglas, Michigan" verbatim used to get destructively repaired down
    # to "The Village" -- a real, but totally unrelated, Oklahoma City
    # suburb literally named "The Village" (confirmed: `_table_lookup
    # ("The Village") == ("place", ["OK"])`). The cut landed right before
    # "of Douglas, Michigan", and the old code treated that "of" as bleed
    # evidence. Correct behavior here is NOT a guessed repair -- "Village"
    # genuinely isn't in any type-word table this module validates city/
    # county names against, so this must stay "unverified", not get
    # silently mangled into a real-but-wrong different state.
    result = je.finalize_jurisdiction("The Village of Douglas, Michigan")
    assert result.jurisdiction == "The Village of Douglas, Michigan"
    assert result.confidence == "unverified"

    # Control: without the leading "The", `_LEADING_TYPE_RE` already
    # strips "Village of " directly during `_table_lookup(base)`'s own
    # candidate generation, so this never even reached `_trim_repair()`'s
    # buggy path -- confirms the fix didn't just get lucky on the "The"
    # form specifically. Also stays "unverified": "Douglas, Michigan"
    # (with the comma) isn't a table key on its own, and "Douglas" alone
    # is a real, ambiguous US city/county-seat name (not resolved without
    # more evidence than this module has here).
    result = je.finalize_jurisdiction("Village of Douglas, Michigan")
    assert result.jurisdiction == "Village of Douglas, Michigan"
    assert result.confidence == "unverified"


def test_looks_like_bleed_does_not_treat_a_leading_of_as_bleed():
    # Direct unit test of the helper itself -- the exact signal
    # `test_finalize_jurisdiction_repairs_douglas_mi_not_the_village_ok()`
    # above depends on. A tail starting with anything else lowercase is
    # still bleed, same as before; only a tail that starts with "of"
    # specifically is now excluded.
    assert je._looks_like_bleed("of Douglas, Michigan") is False
    assert je._looks_like_bleed("to accept and expend the amount of") is True
    assert je._looks_like_bleed("from Council Information Index") is True


def test_extract_jurisdiction_chain_courtenay_bc_not_burlington():
    # Root cause #2. Real eScribe subdomain (pub-courtenay.escribemeetings.com,
    # confirmed live 2026-08-19 -- fetched directly, see BACKLOG_DONE.md's
    # write-up for this entry). The page text below is synthetic (a real
    # Courtenay meeting page fetched live this session carried no "City/
    # County of X" phrase at all -- just a bare venue address, "CVRD Civic
    # Room, 770 Harmston Ave, Courtenay", so the exact real page that
    # produced this misattribution could not be recovered), but reuses two
    # real, confirmed facts: Courtenay, BC is this domain's real, correct
    # jurisdiction, and "Burlington" is a real, validating place name
    # (17 real matches across US states and ON, per
    # `_table_lookup("Burlington")`) that a real page could plausibly
    # mention in an unrelated correspondence item. Before the fix, the
    # stoprule tier accepted "City of Burlington" outright since it
    # validates; now it's cross-checked against the domain's own real
    # subdomain identity ("Courtenay") and rejected, falling through to
    # the (correct) subdomain tier.
    page_text = (
        "Regular Council Meeting Agenda. Correspondence received from the "
        "City of Burlington regarding regional transportation funding. "
        "Item 4.2 Report."
    )
    html = f"<html><body><p>{page_text}</p></body></html>"
    result = je.extract_jurisdiction_chain(
        page_text=page_text,
        html=html,
        url="https://pub-courtenay.escribemeetings.com/Meeting.aspx?Id=1",
    )
    # Ambiguous (BC AND a real North Dakota place both named Courtenay,
    # confirmed via `_table_lookup("Courtenay") == ("place", ["BC",
    # "ND"])`) -- correctly returned bare, no guessed province, same
    # "decline rather than guess" policy this module uses everywhere else.
    assert result == "Courtenay"


def test_extract_jurisdiction_chain_victorville_not_san_bernardino_county():
    # Root cause #2, second confirmed instance. victorville.granicus.com
    # is a real, live Granicus tenant (confirmed live 2026-08-19, and
    # already queued for real ingest -- see
    # scripts/granicus_auto_transcription_queue.txt). Victorville is a
    # real CA city IN San Bernardino County, so a real page easily carries
    # both real, correctly-spelled names -- the bug was purely about which
    # one gets accepted as the meeting's own jurisdiction, not either name
    # being fake. Page text is synthetic (the real page that produced this
    # misattribution could not be recovered), reusing the real,
    # subdomain-confirmed relationship.
    page_text = (
        "This channel is provided in partnership with the County of San "
        "Bernardino transportation authority. City of Victorville City "
        "Council Regular Meeting."
    )
    html = f"<html><body><p>{page_text}</p></body></html>"
    result = je.extract_jurisdiction_chain(
        page_text=page_text,
        html=html,
        url="https://victorville.granicus.com/player/clip/2022",
    )
    assert result == "Victorville, CA"


def test_extract_jurisdiction_chain_agreeing_candidate_is_unaffected():
    # Control for the cross-check fix above: when the text-mined
    # candidate AGREES with the URL's own subdomain identity (the
    # overwhelmingly common real case), the cross-check must be a pure
    # no-op -- this is really just re-confirming
    # test_extract_jurisdiction_chain_stoprule_repairs_a_real_bleed_case()
    # (hercules.granicus.com) still passes with the new code path
    # threaded through, stated explicitly here as its own regression
    # guard.
    page_text = "Welcome. Meeting of the City of Hercules. XIV. PUBLIC COMMUNICATIONS XV. ADJOURNMENT"
    result = je.extract_jurisdiction_chain(
        page_text=page_text,
        html=f"<html>{page_text}</html>",
        url="https://hercules.granicus.com/player/clip/1306",
    )
    assert result == "City of Hercules, CA"


def test_extract_jurisdiction_chain_no_subdomain_hint_is_unaffected():
    # Control: when the URL carries no validating subdomain hint at all
    # (most Swagit/CivicClerk/generic_fallback pages -- the majority of
    # this chain's real traffic), the cross-check has nothing to compare
    # against and must not suppress an otherwise-good candidate. Confirms
    # the fix's blast radius is limited to pages that DO have a
    # corroborating subdomain signal, not a blanket new restriction.
    html = "<table><td>OKLAHOMA CITY</td><td>FORMAL AGENDA</td></table> City of Oklahoma City<br>more"
    result = je.extract_jurisdiction_chain(
        page_text="no trigger here", html=html, url="https://example.com/clip/1"
    )
    assert result == "City of Oklahoma City, OK"


def test_base_name_key_normalizes_formatting_differences_for_comparison():
    # Direct unit test of the cross-check's comparison helper: it must
    # treat "City of Hercules, CA" and "Hercules" as the same identity
    # (state suffix + leading type word stripped), and "San Bernardino
    # County" and "Victorville" as genuinely different identities.
    assert je._base_name_key("City of Hercules, CA") == je._base_name_key("Hercules")
    assert je._base_name_key("San Bernardino County") == "san bernardino"
    assert je._base_name_key("San Bernardino County") != je._base_name_key(
        "Victorville"
    )


def test_tulare_county_visalia_remains_an_unconfirmed_residual_gap():
    # The 4th BACKLOG.md case, "Tulare County misattributed to Visalia"
    # (Visalia is Tulare County's real, correct county seat) -- honestly
    # NOT confirmed fixed this session. Unlike Courtenay and Victorville
    # above, no real, live, validating subdomain for Tulare County's own
    # meeting hosting could be found (tularecounty.granicus.com,
    # tulare.granicus.com, tularecounty.civicweb.net, and
    # tularecounty.swagit.com were all checked live 2026-08-19 and are
    # either dead or not real Tulare County tenants), so there is no
    # confirmed real URL to build a real regression test against, and
    # `extract_jurisdiction_chain()`'s cross-check fix above only engages
    # when a validating subdomain hint exists to compare against. Even a
    # plausible synthetic "tularecounty.granicus.com" doesn't validate:
    # `wordninja.split("tularecounty")` mis-segments to
    # ['tul','are','county'] rather than ['tulare','county'] (confirmed
    # live), a separate, narrower wordninja dictionary gap, not something
    # this fix addresses. Documented here, not silently dropped, so a
    # later session with the real originating URL can pick this up --
    # left as its own narrower BACKLOG.md entry.
    import wordninja

    assert wordninja.split("tularecounty") == ["tul", "are", "county"]
    assert (
        je._validated_subdomain_extract(
            "https://tularecounty.granicus.com/player/clip/1"
        )
        is None
    )
