"""Coop WebTV (webtv.coop) adapter. Fixtures in tests/fixtures/webtv_coop/ are
real pages captured live on 2026-10-07 (Pointe-Claire, channel 4), trimmed;
each file's first line names its source URL."""

import pytest

from app.platforms import webtv_coop
from app.platforms.base import detect_platform
from app.platforms.webtv_coop import (
    WebtvCoopAssetFinder,
    channel_from_url,
    media_key_from_url,
)
from app.utils.tenant_key import tenant_key

from aiohttp_mock import FakeResponse, mock_session
from conftest import load_fixture

KEY = "1886702ad1fda24b99dcab99fe8a66ea"
CHANNEL_VIDEO_URL = (
    "https://webtv.coop/channel/video/2026-10-06-conseil-de-la-ville-de-pointe-claire"
    f"/{KEY}/4"
)
SITE_VIDEO_URL = (
    f"https://webtv.coop/video/2026-10-06-conseil-de-la-ville-de-pointe-claire/{KEY}"
)
VTT_URL = f"https://webtv.coop/webPlayerSubtitles/subtitleFile/key/{KEY}/filename/fr_subtitles.vtt"
NOCAP_KEY = "f767a2b8607a6fb4de4adad22becc003"
NOCAP_URL = (
    "https://webtv.coop/channel/video/2026-04-07-reconstruction-complte-de-lavenue-"
    f"chestnut/{NOCAP_KEY}/4"
)


@pytest.fixture(autouse=True)
def no_pause(monkeypatch):
    monkeypatch.setattr(webtv_coop, "PAUSE_BETWEEN_REQUESTS_SECONDS", 0)


def _with_captions_routes(url):
    return {
        url: FakeResponse(
            status=200,
            text=load_fixture("webtv_coop", "video_with_captions.html"),
            url=url,
        ),
        VTT_URL: FakeResponse(
            status=200,
            text=load_fixture(
                "webtv_coop", "captions_pointe_claire_2026-10-06_first60.vtt"
            ),
            url=VTT_URL,
        ),
    }


@pytest.mark.parametrize("url", [CHANNEL_VIDEO_URL, SITE_VIDEO_URL])
async def test_resolve_video_with_captions_both_address_shapes(url):
    with mock_session(_with_captions_routes(url)):
        result = await WebtvCoopAssetFinder().resolve(url)

    assert result.platform == "webtv_coop"
    assert result.external_id == f"webtv_coop:{KEY}"
    assert result.title == "2026-10-06 Conseil de la Ville de Pointe-Claire"
    assert result.date == "2026-10-06"
    assert result.video_format == "m3u8"
    assert result.video_url == (
        "https://5976193b91256.streamlock.net/vod/"
        f"smil:{KEY}_1791337581.smil/playlist.m3u8?1791411162"
    )
    assert result.video_duration_seconds == 7405.0
    # Only the channel address names its channel. The site-wide page does
    # not (its /channel/ links are site navigation), so no hint is sent.
    assert result.video_channel == ("webtv_coop:4" if "/channel/" in url else None)
    assert result.transcript_language == "fr"
    assert len(result.segments) == 60
    assert result.segments[0].text.startswith("Bonsoir")
    assert result.alternate_transcripts == []
    assert result.transcript_warnings == []


async def test_resolve_video_without_captions_has_no_segments_and_does_not_fail():
    routes = {
        NOCAP_URL: FakeResponse(
            status=200,
            text=load_fixture("webtv_coop", "video_without_captions.html"),
            url=NOCAP_URL,
        )
    }
    with mock_session(routes):
        result = await WebtvCoopAssetFinder().resolve(NOCAP_URL)

    assert result.segments == []
    assert result.video_format == "m3u8"
    assert result.video_duration_seconds == 983.0
    assert result.date == "2026-04-07"
    assert result.transcript_warnings == ["No captions found for this video."]
    assert result.video_warnings == []


async def test_two_caption_files_first_listed_is_primary_and_the_other_is_kept():
    # SYNTHETIC: the real page above lists one caption file. This adds a
    # second <track> line (same shape as the real one) to exercise the
    # two-file rule. A real two-file video (one Pointe-Claire video has de
    # and fr, per the 2026-10-07 live check) was not captured.
    html = load_fixture("webtv_coop", "video_with_captions.html").replace(
        "</video-js>",
        f'<track src="/webPlayerSubtitles/subtitleFile/key/{KEY}/filename/en_subtitles.vtt"'
        ' srclang="en" kind="captions" label="English" /></video-js>',
    )
    en_url = VTT_URL.replace("fr_subtitles", "en_subtitles")
    routes = _with_captions_routes(CHANNEL_VIDEO_URL)
    routes[CHANNEL_VIDEO_URL] = FakeResponse(
        status=200, text=html, url=CHANNEL_VIDEO_URL
    )
    routes[en_url] = FakeResponse(
        status=200,
        text="WEBVTT - generated by WEBTV.COOP\n\n1\n00:00:01.000 --> 00:00:03.000\nGood evening, everyone.\n",
        url=en_url,
    )
    with mock_session(routes):
        result = await WebtvCoopAssetFinder().resolve(CHANNEL_VIDEO_URL)

    assert result.transcript_language == "fr"
    assert len(result.segments) == 60
    assert [a.language for a in result.alternate_transcripts] == ["en"]
    assert result.alternate_transcripts[0].segments[0].text == "Good evening, everyone."


async def test_caption_file_404_resolves_with_a_warning():
    routes = _with_captions_routes(CHANNEL_VIDEO_URL)
    routes[VTT_URL] = FakeResponse(status=404, url=VTT_URL)
    with mock_session(routes):
        result = await WebtvCoopAssetFinder().resolve(CHANNEL_VIDEO_URL)
    assert result.segments == []
    assert result.video_url
    assert result.transcript_warnings == ["No captions found for this video."]


async def test_429_stops_with_a_plain_warning():
    routes = {CHANNEL_VIDEO_URL: FakeResponse(status=429, url=CHANNEL_VIDEO_URL)}
    with mock_session(routes):
        result = await WebtvCoopAssetFinder().resolve(CHANNEL_VIDEO_URL)
    assert result.video_url is None
    assert "429" in result.video_warnings[0]


async def test_channel_page_is_not_a_video_and_makes_no_request():
    url = "https://webtv.coop/channel/Pointe2DClaire/4"
    with mock_session({}):
        result = await WebtvCoopAssetFinder().resolve(url)
    assert result.video_url is None
    assert "not a single video" in result.video_warnings[0]


def test_address_helpers_and_tenant_key():
    assert media_key_from_url(CHANNEL_VIDEO_URL) == KEY
    assert media_key_from_url(SITE_VIDEO_URL) == KEY
    assert media_key_from_url("https://webtv.coop/channel/Pointe2DClaire/4") is None
    assert channel_from_url(CHANNEL_VIDEO_URL) == "4"
    assert channel_from_url("https://webtv.coop/channel/Pointe2DClaire/4") == "4"
    assert channel_from_url(SITE_VIDEO_URL) is None
    assert tenant_key(CHANNEL_VIDEO_URL) == "4"
    assert tenant_key("https://webtv.coop/channel/Pointe2DClaire/4") == "4"
    assert tenant_key("https://webtv.coop/channel/Saint2DLaurent/6") == "6"
    # Never "the whole host": the site-wide address names no channel.
    assert tenant_key(SITE_VIDEO_URL) is None


def test_channel_page_fixture_lists_both_video_shapes_the_adapter_reads():
    html = load_fixture("webtv_coop", "channel_pointe_claire_4.html")
    links = [
        part.split('"')[0]
        for part in html.split('href="')[1:]
        if part.startswith("/channel/video/")
    ]
    assert len(links) == 15
    assert all(media_key_from_url("https://webtv.coop" + link) for link in links)
    assert all(channel_from_url("https://webtv.coop" + link) == "4" for link in links)


@pytest.mark.parametrize(
    "url",
    [
        CHANNEL_VIDEO_URL,
        SITE_VIDEO_URL,
        "https://webtv.coop/channel/Pointe2DClaire/4",
        "https://www.webtv.coop/channel/Beaconsfield/1",
    ],
)
def test_detect_platform_routes_webtv_coop(url):
    assert detect_platform(url) == "webtv_coop"


def test_pins_resolve_a_channel_to_its_government():
    from app.utils.gov_registry.resolver import page_hints_for, resolve_government

    # Pointe-Claire, channel 4 -> ca:csd:2466097 (tenant_overrides.csv). The
    # site-wide address carries no channel, so the pin fires from the
    # adapter's video_channel hint; the channel address fires by its number.
    for path, channel in (
        (f"/video/x/{KEY}", "webtv_coop:4"),
        (f"/channel/video/x/{KEY}/4", None),
    ):
        match = resolve_government(
            None,
            tenant_host="webtv.coop",
            path=path,
            page_hints=page_hints_for("webtv_coop", f"webtv_coop:{KEY}", channel),
        )
        assert match.gov_id == "ca:csd:2466097"
        assert match.tier == "pinned"


def test_an_unpinned_channel_stays_unresolved():
    from app.utils.gov_registry.resolver import page_hints_for, resolve_government

    # Channels 6 (Saint-Laurent) and 7 (Sud-Ouest) are Montreal boroughs
    # with no id of their own in ca_csd.csv, so they are not pinned.
    match = resolve_government(
        None,
        tenant_host="webtv.coop",
        path=f"/video/x/{KEY}",
        page_hints=page_hints_for("webtv_coop", f"webtv_coop:{KEY}", "webtv_coop:6"),
    )
    assert match.tier == "blank"


def test_site_wide_address_with_no_channel_stays_unresolved():
    from app.utils.gov_registry.resolver import page_hints_for, resolve_government

    match = resolve_government(
        None,
        tenant_host="webtv.coop",
        path=f"/video/x/{KEY}",
        page_hints=page_hints_for("webtv_coop", f"webtv_coop:{KEY}", None),
    )
    assert match.tier == "blank"


def test_site_wide_page_title_and_nav_links_are_not_read_as_the_channel():
    # A trimmed shape of the real site-wide page captured 2026-10-07 from
    # https://webtv.coop/video/2026-04-07-reconstruction-complte-de-lavenue-
    # chestnut/f767a2b8607a6fb4de4adad22becc003 : a different <h1> class,
    # a "- Média - WEBTV.COOP" title, and site-navigation links to channels
    # 12 and 13 (neither is this video's channel).
    html = (
        "<title>2026-04-07 - Reconstruction complète de l’avenue Chestnut - Média - WEBTV.COOP\n</title>"
        '<a class="channelLink" href="/channel/Production-ISCA/12">x</a>'
        '<a class="channelLink" href="/channel/La-coop-WEBTV/13">x</a>'
    )
    assert WebtvCoopAssetFinder._title(html) == (
        "2026-04-07 - Reconstruction complète de l’avenue Chestnut"
    )
    html += '<h1 class="no-indent media-title">2026-04-07 - Titre</h1>'
    assert WebtvCoopAssetFinder._title(html) == "2026-04-07 - Titre"
