"""Tests for app/utils/jurisdiction_enrich.py -- the shared "fill in a
missing state" module backed by real US Census Bureau Gazetteer/
relationship data (app/utils/jurisdiction_data/*.csv, generated by
scripts/build_jurisdiction_data.py). Every value asserted against here is
real, checked directly in the generated CSVs while building this module,
not synthetic.
"""

from app.utils import jurisdiction_enrich as je


def test_lookup_county_state_resolves_a_unique_name():
    assert je.lookup_county_state("Sonoma County") == "CA"
    assert je.lookup_county_state("Napa County") == "CA"


def test_lookup_county_state_normalizes_bare_and_prefixed_forms():
    # Bare name, "County of X", and the full "X County" form should all
    # key to the same real entry.
    assert je.lookup_county_state("Sonoma") == "CA"
    assert je.lookup_county_state("County of Sonoma") == "CA"
    assert je.lookup_county_state("sonoma county") == "CA"


def test_lookup_county_state_returns_none_for_a_real_collision():
    # Real, confirmed: "Washington County" exists in 30+ states -- must
    # not guess one.
    assert je.lookup_county_state("Washington County") is None


def test_lookup_county_state_returns_none_for_an_unknown_name():
    assert je.lookup_county_state("Not A Real County Zzyzx") is None


def test_lookup_city_state_resolves_a_unique_name():
    assert je.lookup_city_state("Chicago") == "IL"
    assert je.lookup_city_state("City of Chicago") == "IL"


def test_lookup_city_state_does_not_double_strip_a_name_that_legitimately_ends_in_city():
    # Real bug found and fixed 2026-08-12: "City of Oklahoma City" used to
    # lose its leading "City of " correctly, then *also* lose the
    # trailing "City" that's genuinely part of the real proper name --
    # landing on the wrong lookup key "Oklahoma", which collided with a
    # real, different place ("Oklahoma borough, PA") and silently
    # returned PA instead of OK. Real pattern, not a one-off: Carson
    # City, Jersey City, and Rapid City all have the same shape.
    assert je.lookup_city_state("City of Oklahoma City") == "OK"
    assert je.lookup_city_state("Oklahoma City") == "OK"


def test_lookup_city_state_resolves_real_consolidated_city_county_governments():
    # Real gap found and fixed 2026-08-15: build_jurisdiction_data.py's
    # build_places() only kept Census FUNCSTAT "A" (active incorporated
    # government) rows, silently dropping every real consolidated
    # city-county government -- Census codes these "B" (Baton Rouge,
    # Lafayette) or "F" ("... (balance)" statistical-area rows), not "A".
    # Confirmed against the real 2024 Gazetteer file (see
    # build_places()'s own comment for the full FUNCSTAT list). All 8 "F"
    # rows are asserted here, not just one -- this was a closed, verified
    # list at fix time, not a general pattern to trust blindly.
    assert je.lookup_city_state("Nashville-Davidson") == "TN"
    assert je.lookup_city_state("Indianapolis") == "IN"
    assert je.lookup_city_state("Louisville/Jefferson County") == "KY"
    assert je.lookup_city_state("Athens-Clarke County") == "GA"
    assert je.lookup_city_state("Augusta-Richmond County") == "GA"
    assert je.lookup_city_state("Butte-Silver Bow") == "MT"
    assert je.lookup_city_state("Baton Rouge") == "LA"


def test_lookup_city_state_does_not_over_strip_a_consolidated_government_name():
    # Real bug caught while fixing the gap above: naively applying the
    # normal trailing-type-word strip AFTER already stripping "unified
    # government (balance)" turned "Greeley County unified government
    # (balance)" into just "greeley" -- colliding with three unrelated
    # real cities named Greeley (CO, IA, KS) and making an otherwise-
    # unambiguous county lookup falsely ambiguous. "County" here is part
    # of the real name (a *county* consolidated government, distinct from
    # any city sharing the root name), same trap as Oklahoma City above.
    assert je.lookup_city_state("Greeley County") == "KS"
    # Plain "Greeley" must still correctly stay ambiguous -- this fix must
    # not accidentally make the collision worse in the other direction.
    assert je.lookup_city_state("Greeley") is None


def test_lookup_city_state_returns_none_for_real_collisions():
    # Real, confirmed: "Detroit" is a real city in MI, OR, AL, and TX;
    # "Charlotte" in NC, MI, IA, TX, and TN -- the exact real example this
    # module's design was built around (see lookup_by_domain() below for
    # how these two specific instances actually get resolved anyway).
    assert je.lookup_city_state("Detroit") is None
    assert je.lookup_city_state("Charlotte") is None


def test_lookup_city_state_returns_none_for_kansas_city():
    # A genuinely famous case, not just an obscure name collision --
    # Kansas City is a real, substantial, separately-incorporated city in
    # *both* Kansas and Missouri. Correctly stays unresolved either way.
    assert je.lookup_city_state("Kansas City") is None
    assert je.lookup_city_state("City of Kansas City") is None


def test_lookup_county_by_zip_resolves_a_real_zip():
    # Real Santa Rosa, CA ZIP, sitting inside Sonoma County.
    result = je.lookup_county_by_zip("95403")
    assert result == ("Sonoma County", "CA")


def test_lookup_county_by_zip_picks_the_larger_overlap_on_a_real_multi_county_zip():
    # Real ZCTA 94952 genuinely spans both Marin and Sonoma counties;
    # Marin's real overlap area is larger (confirmed in the generated
    # data: 264,775,970 vs 249,379,622) -- must pick Marin, not just the
    # first/alphabetically-first candidate.
    result = je.lookup_county_by_zip("94952")
    assert result == ("Marin County", "CA")


def test_lookup_county_by_zip_returns_none_for_a_non_zcta():
    assert je.lookup_county_by_zip("00000") is None


def test_lookup_place_by_zip_resolves_a_real_zip():
    result = je.lookup_place_by_zip("95403")
    assert result == ("Santa Rosa city", "CA")


def test_county_and_place_zip_lookups_can_legitimately_disagree():
    # The real trap this whole module is built around: 95403's county
    # answer (Sonoma County) and place answer (Santa Rosa city) are both
    # correct, but answer different questions -- a caller must pick
    # based on which TYPE it already knows this jurisdiction to be, never
    # let the city-shaped address silently stand in for the county.
    county = je.lookup_county_by_zip("95403")
    place = je.lookup_place_by_zip("95403")
    assert county[0] != place[0]
    assert county[1] == place[1] == "CA"  # same state either way


def test_find_zip_addresses_extracts_real_address_shape():
    # Real address confirmed live on a real PrimeGov page (Thousand
    # Oaks, CA) -- see tests/test_primegov.py's TOAKS_HEADER_HTML.
    text = "Andrew P. Fox City Council Chambers, 2100 E. Thousand Oaks Blvd., Thousand Oaks, CA 91362"
    assert je.find_zip_addresses(text) == [("Thousand Oaks", "CA", "91362")]


def test_find_zip_addresses_handles_zip_plus_four():
    text = "123 Main St, Sonoma, CA 95476-1234"
    assert je.find_zip_addresses(text) == [("Sonoma", "CA", "95476")]


def test_find_zip_addresses_returns_multiple_real_matches():
    text = "Main office: 1 Fiscal Dr, Santa Rosa, CA 95403. Branch: 123 Elm St, Napa, CA 94559."
    assert je.find_zip_addresses(text) == [
        ("Santa Rosa", "CA", "95403"),
        ("Napa", "CA", "94559"),
    ]


def test_find_zip_addresses_returns_empty_list_for_no_match():
    assert je.find_zip_addresses("No address here at all.") == []


def test_lookup_by_domain_resolves_a_confirmed_real_customer():
    known = je.lookup_by_domain("detroit-vod.cablecast.tv")
    assert known == je.KnownJurisdiction("Detroit", "city", "MI")


def test_lookup_by_domain_is_case_insensitive():
    assert je.lookup_by_domain("DETROIT-VOD.CABLECAST.TV").state == "MI"


def test_lookup_by_domain_returns_none_for_an_unconfirmed_domain():
    assert je.lookup_by_domain("some-random-city.example.com") is None


def test_resolve_state_prefers_a_confirmed_domain_over_an_ambiguous_name():
    # "Detroit" alone is unresolvable (real collision, see above) -- the
    # confirmed domain is what actually makes this resolve.
    assert je.resolve_state("Detroit", "city", netloc="detroit-vod.cablecast.tv") == "MI"


def test_resolve_state_falls_back_to_name_lookup_without_a_domain():
    assert je.resolve_state("Sonoma County", "county") == "CA"


def test_resolve_state_falls_back_to_zip_in_page_text_when_name_lookup_fails():
    # No confirmed domain, and the name itself ("Sonoma") isn't passed at
    # all here -- only a real address in the page text to go on, exactly
    # the "adapter found no state anywhere except a printed address" case
    # this module exists for.
    page_text = "Contact us: 575 Administration Dr, Santa Rosa, CA 95403"
    assert je.resolve_state(None, "county", page_text=page_text) == "CA"


def test_resolve_state_scopes_zip_lookup_to_the_caller_declared_type():
    # The real trap: a county-type caller must get the COUNTY crosswalk's
    # answer from a ZIP-in-text, not silently borrow the place crosswalk's
    # answer just because it's also a valid real place. Both answers give
    # the same real state here (CA), but the underlying lookup called
    # must be the county one -- verified indirectly via the "county" type
    # correctly still resolving at all for an address whose city portion
    # doesn't share Sonoma County's own name.
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    state = je.resolve_state("Sonoma", "county", page_text=page_text)
    assert state == "CA"


def test_resolve_state_returns_none_when_nothing_resolves():
    assert je.resolve_state("Not A Real Place Zzyzx", "city") is None
    assert je.resolve_state(None, "city") is None


def test_enrich_jurisdiction_text_appends_state_for_an_unambiguous_city():
    assert je.enrich_jurisdiction_text("City of Napa") == "City of Napa, CA"


def test_enrich_jurisdiction_text_detects_county_type_from_the_text_itself():
    assert je.enrich_jurisdiction_text("Sonoma County") == "Sonoma County, CA"


def test_enrich_jurisdiction_text_uses_a_confirmed_domain():
    assert je.enrich_jurisdiction_text("Detroit", netloc="detroit-vod.cablecast.tv") == "Detroit, MI"


def test_enrich_jurisdiction_text_falls_back_to_zip_in_page_text():
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    assert je.enrich_jurisdiction_text("Sonoma County", page_text=page_text) == "Sonoma County, CA"


def test_enrich_jurisdiction_text_leaves_ambiguous_names_unchanged():
    assert je.enrich_jurisdiction_text("City of Alexandria") == "City of Alexandria"


def test_enrich_jurisdiction_text_skips_falsy_values():
    assert je.enrich_jurisdiction_text(None) is None
    assert je.enrich_jurisdiction_text("") == ""


def test_enrich_jurisdiction_text_skips_a_value_that_already_has_a_comma():
    assert je.enrich_jurisdiction_text("League City, TX") == "League City, TX"


def test_enrich_jurisdiction_text_skips_a_callers_placeholder():
    assert je.enrich_jurisdiction_text("Unknown Jurisdiction", placeholder="Unknown Jurisdiction") == "Unknown Jurisdiction"


def test_enrich_jurisdiction_text_resolves_alexandria_via_confirmed_domain():
    # Confirmed live 2026-08-13: "Alexandria" alone stays ambiguous (see
    # test_enrich_jurisdiction_text_leaves_ambiguous_names_unchanged
    # above), but alexandria.granicus.com is a confirmed real customer.
    assert je.enrich_jurisdiction_text(
        "City of Alexandria", netloc="alexandria.granicus.com"
    ) == "City of Alexandria, VA"


def test_known_jurisdiction_display_builds_full_string_for_a_confirmed_domain():
    assert je.known_jurisdiction_display("slc.primegov.com") == "City of Salt Lake City, UT"


def test_known_jurisdiction_display_is_case_insensitive():
    assert je.known_jurisdiction_display("SLC.PRIMEGOV.COM") == "City of Salt Lake City, UT"


def test_known_jurisdiction_display_returns_none_for_an_unconfirmed_domain():
    assert je.known_jurisdiction_display("some-random-city.example.com") is None


# --- finalize_jurisdiction() -- ingest-time validation/repair/split,
# built from the 2026-08-15 audit of all 649 real archived jurisdiction
# values. See JURISDICTION_METADATA_PLAN.md for the full design and
# BACKLOG.md's "Census-table baseline validation" entry for the data this
# was tuned against. Every case below is a real value pulled from that
# audit, not invented.

def test_finalize_jurisdiction_validates_a_clean_name_unchanged():
    result = je.finalize_jurisdiction("City of Sunnyvale, CA")
    assert result.jurisdiction == "City of Sunnyvale, CA"
    assert result.meeting_body is None
    assert result.confidence == "validated"


def test_table_lookup_recognizes_a_page_authored_abbreviation():
    # "Ft. Worth" is how real pages actually write it (user's own call,
    # 2026-08-15 -- see _STOPRULE_ABBREV_OK's comment); the Census table's
    # own key is the spelled-out "Fort Worth". Added specifically so
    # extract_jurisdiction_chain()'s validation gate (which requires a
    # candidate to actually validate before being accepted) doesn't
    # reject every abbreviated real name it was built to preserve.
    assert je._table_lookup("Ft. Worth") == ("place", ["TX"])
    assert je._table_lookup("Mt. Vernon") is not None
    assert je.finalize_jurisdiction("City of Ft. Worth").confidence == "validated"


def test_finalize_jurisdiction_repairs_trailing_bleed():
    # Real value, Hercules CA's Granicus page -- the still-open
    # granicus.py body-regex bug (BACKLOG.md) let agenda-heading text run
    # on past the real city name.
    result = je.finalize_jurisdiction(
        "City of Hercules. XIV. PUBLIC COMMUNICATIONS XV.", netloc="hercules.granicus.com"
    )
    assert result.jurisdiction == "City of Hercules"
    assert result.meeting_body is None
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_preserves_state_suffix_through_a_repair():
    result = je.finalize_jurisdiction("City of Boston to accept and expend the amount of, MA")
    assert result.jurisdiction == "City of Boston, MA"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_never_trims_a_legitimately_long_real_name():
    # Real value, a real Bay Area agency -- trimming from the right would
    # eventually hit "Bay" (a real place), but nothing in the discarded
    # tail looks like bleed, so this must be left whole.
    result = je.finalize_jurisdiction("Bay Area Headquarters Authority")
    assert result.jurisdiction == "Bay Area Headquarters Authority"
    assert result.meeting_body is None
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_splits_a_real_entity_prefix():
    # Real value, hacsc.granicus.com -- "Housing Authority" is a real,
    # distinct governing body, not bleed; splitting it out (rather than
    # discarding it, or leaving the whole string un-validatable) is the
    # correct outcome per JURISDICTION_METADATA_PLAN.md's design.
    result = je.finalize_jurisdiction("Housing Authority of the County of Santa Clara")
    assert result.jurisdiction == "County of Santa Clara"
    assert result.meeting_body == "Housing Authority"
    assert result.confidence == "repaired"


def test_finalize_jurisdiction_does_not_split_off_a_bare_type_phrase():
    # Real bug caught testing this fix against all 649 archived rows:
    # "The City of Memphis" and "City and County of Denver" both look
    # like the entity-split shape, but "The City"/"City and County" are
    # not real distinct entities, just the ordinary jurisdiction-type
    # phrasing -- splitting them off would produce meaningless bodies.
    result = je.finalize_jurisdiction("The City of Memphis, TN")
    assert result.meeting_body is None
    assert result.jurisdiction == "The City of Memphis, TN"

    result = je.finalize_jurisdiction("City and County of San Francisco")
    assert result.meeting_body is None
    assert result.jurisdiction == "City and County of San Francisco"


def test_finalize_jurisdiction_authoritative_domain_overrides_even_a_plausible_extraction():
    # The real Holladay bug this design exists to close: PrimeGov's own
    # text extraction on slc.primegov.com sometimes finds a genuine,
    # table-valid *wrong* city ("City of Holladay, UT" -- Holladay is a
    # real Utah city) instead of the real header. Table validation alone
    # can never catch a plausible-but-wrong value; only an authoritative
    # domain override can.
    result = je.finalize_jurisdiction("City of Holladay, UT", netloc="slc.primegov.com")
    assert result.jurisdiction == "Salt Lake City, UT"
    assert result.confidence == "authoritative"


def test_finalize_jurisdiction_authoritative_domain_fills_a_blank_too():
    result = je.finalize_jurisdiction(None, netloc="slc.primegov.com")
    assert result.jurisdiction == "Salt Lake City, UT"
    assert result.confidence == "authoritative"


def test_finalize_jurisdiction_fallback_domain_fires_on_blank_or_unvalidated_extraction():
    # A "fallback"-strength entry fires whenever extraction leaves nothing
    # usable -- blank, or present but not table-valid -- unlike
    # "authoritative", which overrides even a plausible-looking real
    # extraction (see the Holladay test above). This is deliberately
    # different from "only when blank": alexandria.granicus.com is
    # registered because this single-tenant customer is confirmed to
    # always be Alexandria, VA, so an unvalidatable extraction on this
    # specific host is still safer to answer from the registry than to
    # leave unverified.
    result = je.finalize_jurisdiction(None, netloc="alexandria.granicus.com")
    assert result.jurisdiction == "Alexandria, VA"
    assert result.confidence == "fallback"

    result = je.finalize_jurisdiction("Not A Real Place Zzyzx", netloc="alexandria.granicus.com")
    assert result.jurisdiction == "Alexandria, VA"
    assert result.confidence == "fallback"


def test_finalize_jurisdiction_does_not_consult_an_unregistered_domain():
    result = je.finalize_jurisdiction("Some Unvalidatable Text", netloc="totally-unknown-host.example.com")
    assert result.jurisdiction == "Some Unvalidatable Text"
    assert result.confidence == "unverified"


def test_finalize_jurisdiction_returns_blank_confidence_for_nothing_at_all():
    result = je.finalize_jurisdiction(None)
    assert result.jurisdiction is None
    assert result.confidence == "blank"


# --- extract_jurisdiction_chain() (2026-08-15, workstream 2 promotions) ---
# Shared fallback chain for adapters with no bespoke extraction (Swagit,
# generic_fallback) -- see the module-level comment above
# extract_jurisdiction_chain() in jurisdiction_enrich.py for the tournament
# results these three tiers are promoted from.


def test_extract_jurisdiction_chain_stoprule_repairs_a_real_bleed_case():
    # The real Hercules bleed confirmed live 2026-08-15 (see BACKLOG.md's
    # "Granicus jurisdiction bleed" entry): the shipped body regex has no
    # sentence boundary and runs straight into an agenda's roman-numeral
    # list. The stop rule fixes this at the source, before the enricher's
    # own repair machinery would even need to run.
    page_text = "Welcome. Meeting of the City of Hercules. XIV. PUBLIC COMMUNICATIONS XV. ADJOURNMENT"
    result = je.extract_jurisdiction_chain(
        page_text=page_text, html=f"<html>{page_text}</html>", url="https://hercules.granicus.com/player/clip/1306"
    )
    assert result == "City of Hercules, CA"


def test_extract_jurisdiction_chain_stoprule_keeps_a_real_abbreviation():
    page_text = "Agenda for the City of Ft. Worth regular council session"
    result = je.extract_jurisdiction_chain(page_text=page_text, html="", url="https://example.granicus.com/clip/1")
    assert result == "City of Ft. Worth"


def test_extract_jurisdiction_chain_falls_back_to_capitalization_walk():
    # No "City/County/Town of" trigger for the stop rule to find in plain
    # text, but the tag-bounded walk (mirrors PrimeGov's own shipped
    # regex) finds it in the raw markup.
    # ("Oklahoma City" is nationally unambiguous, so
    # enrich_jurisdiction_text() correctly appends its real state too.)
    html = "<table><td>OKLAHOMA CITY</td><td>FORMAL AGENDA</td></table> City of Oklahoma City<br>more"
    result = je.extract_jurisdiction_chain(page_text="no trigger here", html=html, url="https://example.com/clip/1")
    assert result == "City of Oklahoma City, OK"


def test_extract_jurisdiction_chain_falls_back_to_validated_subdomain():
    # Real case this tier exists for: wordninja over-splits "galesburg"
    # into "Gales Burg" (a real, confirmed bug this session, not
    # hypothetical -- see BACKLOG.md), which never validates. Checking the
    # raw unsplit label first fixes it without needing wordninja at all.
    result = je.extract_jurisdiction_chain(
        page_text="no trigger", html="<html>no trigger</html>", url="https://galesburg.granicus.com/player/clip/1"
    )
    assert result == "Galesburg"


def test_extract_jurisdiction_chain_subdomain_resolves_state_via_registry():
    # sandiego.granicus.com is a real, already-registered known domain --
    # confirms the subdomain tier's candidate is run through
    # enrich_jurisdiction_text() (which consults the registry), not
    # returned bare, since "San Diego" alone is nationally ambiguous
    # (CA and TX both have a real "San Diego").
    result = je.extract_jurisdiction_chain(
        page_text="no trigger", html="<html>no trigger</html>", url="https://sandiego.granicus.com/player/clip/1"
    )
    assert result == "San Diego, CA"


def test_extract_jurisdiction_chain_rejects_a_capitalization_walk_false_positive():
    # Real, confirmed-live bug (2026-08-15, found while dry-running the
    # workstream 4 backfill against real cached HTML, not hypothetical):
    # a Broward MPO Swagit page (browardmpo.new.swagit.com/videos/359517)
    # has an ALL-CAPS caption line of spoken testimony -- "...IN THE CITY
    # OF FORT LAUDERDALE THAT'S IDENTIFIED..." -- that the capitalization
    # walk matched into, producing "City of Fort Lauderdale That'S
    # Identified." That candidate doesn't validate (nor trim-repair,
    # since "That'S"/"Identified" show no bleed signal -- both are
    # capitalized, so _looks_like_bleed() correctly refuses to guess
    # which prefix is real) and must be discarded, not stored -- a real
    # city mention inside spoken dialogue is not evidence of the
    # meeting's own jurisdiction.
    page_text = (
        "ALSO, THE S. MIDDLE RIVER MOBILITY PROJECT IN THE CITY OF FORT LAUDERDALE THAT'S "
        "IDENTIFIED. Next item on the agenda."
    )
    html = f"<html><body><p>{page_text}</p></body></html>"
    result = je.extract_jurisdiction_chain(
        page_text="no trigger for the stop rule here", html=html, url="https://browardmpo.new.swagit.com/videos/1"
    )
    assert result is None


def test_extract_jurisdiction_chain_declines_rather_than_guesses():
    # No trigger phrase, no tag-bounded match, and a subdomain that
    # doesn't validate against any real place/county -- every tier
    # declines, so the chain returns None rather than fabricating
    # something.
    result = je.extract_jurisdiction_chain(
        page_text="nothing useful here", html="<html>nothing useful here</html>",
        url="https://totallymadeupgarbage999.example.com/clip/1",
    )
    assert result is None
