"""Tests for app/utils/jurisdiction_enrich.py -- the shared "fill in a
missing state" module backed by real US Census Bureau Gazetteer/
relationship data (app/utils/jurisdiction_data/*.csv, generated by
scripts/build_jurisdiction_data.py). Every value asserted against here is
real, checked directly in the generated CSVs while building this module,
not synthetic.
"""

from app.utils import jurisdiction_enrich as je


def test_lookup_county_state_resolves_a_unique_name():
    assert je.lookup_county_state("Sonoma County") == "CA"
    assert je.lookup_county_state("Napa County") == "CA"


def test_lookup_county_state_normalizes_bare_and_prefixed_forms():
    # Bare name, "County of X", and the full "X County" form should all
    # key to the same real entry.
    assert je.lookup_county_state("Sonoma") == "CA"
    assert je.lookup_county_state("County of Sonoma") == "CA"
    assert je.lookup_county_state("sonoma county") == "CA"


def test_lookup_county_state_returns_none_for_a_real_collision():
    # Real, confirmed: "Washington County" exists in 30+ states -- must
    # not guess one.
    assert je.lookup_county_state("Washington County") is None


def test_lookup_county_state_returns_none_for_an_unknown_name():
    assert je.lookup_county_state("Not A Real County Zzyzx") is None


def test_lookup_city_state_resolves_a_unique_name():
    assert je.lookup_city_state("Chicago") == "IL"
    assert je.lookup_city_state("City of Chicago") == "IL"


def test_lookup_city_state_does_not_double_strip_a_name_that_legitimately_ends_in_city():
    # Real bug found and fixed 2026-08-12: "City of Oklahoma City" used to
    # lose its leading "City of " correctly, then *also* lose the
    # trailing "City" that's genuinely part of the real proper name --
    # landing on the wrong lookup key "Oklahoma", which collided with a
    # real, different place ("Oklahoma borough, PA") and silently
    # returned PA instead of OK. Real pattern, not a one-off: Carson
    # City, Jersey City, and Rapid City all have the same shape.
    assert je.lookup_city_state("City of Oklahoma City") == "OK"
    assert je.lookup_city_state("Oklahoma City") == "OK"


def test_lookup_city_state_returns_none_for_real_collisions():
    # Real, confirmed: "Detroit" is a real city in MI, OR, AL, and TX;
    # "Charlotte" in NC, MI, IA, TX, and TN -- the exact real example this
    # module's design was built around (see lookup_by_domain() below for
    # how these two specific instances actually get resolved anyway).
    assert je.lookup_city_state("Detroit") is None
    assert je.lookup_city_state("Charlotte") is None


def test_lookup_city_state_returns_none_for_kansas_city():
    # A genuinely famous case, not just an obscure name collision --
    # Kansas City is a real, substantial, separately-incorporated city in
    # *both* Kansas and Missouri. Correctly stays unresolved either way.
    assert je.lookup_city_state("Kansas City") is None
    assert je.lookup_city_state("City of Kansas City") is None


def test_lookup_county_by_zip_resolves_a_real_zip():
    # Real Santa Rosa, CA ZIP, sitting inside Sonoma County.
    result = je.lookup_county_by_zip("95403")
    assert result == ("Sonoma County", "CA")


def test_lookup_county_by_zip_picks_the_larger_overlap_on_a_real_multi_county_zip():
    # Real ZCTA 94952 genuinely spans both Marin and Sonoma counties;
    # Marin's real overlap area is larger (confirmed in the generated
    # data: 264,775,970 vs 249,379,622) -- must pick Marin, not just the
    # first/alphabetically-first candidate.
    result = je.lookup_county_by_zip("94952")
    assert result == ("Marin County", "CA")


def test_lookup_county_by_zip_returns_none_for_a_non_zcta():
    assert je.lookup_county_by_zip("00000") is None


def test_lookup_place_by_zip_resolves_a_real_zip():
    result = je.lookup_place_by_zip("95403")
    assert result == ("Santa Rosa city", "CA")


def test_county_and_place_zip_lookups_can_legitimately_disagree():
    # The real trap this whole module is built around: 95403's county
    # answer (Sonoma County) and place answer (Santa Rosa city) are both
    # correct, but answer different questions -- a caller must pick
    # based on which TYPE it already knows this jurisdiction to be, never
    # let the city-shaped address silently stand in for the county.
    county = je.lookup_county_by_zip("95403")
    place = je.lookup_place_by_zip("95403")
    assert county[0] != place[0]
    assert county[1] == place[1] == "CA"  # same state either way


def test_find_zip_addresses_extracts_real_address_shape():
    # Real address confirmed live on a real PrimeGov page (Thousand
    # Oaks, CA) -- see tests/test_primegov.py's TOAKS_HEADER_HTML.
    text = "Andrew P. Fox City Council Chambers, 2100 E. Thousand Oaks Blvd., Thousand Oaks, CA 91362"
    assert je.find_zip_addresses(text) == [("Thousand Oaks", "CA", "91362")]


def test_find_zip_addresses_handles_zip_plus_four():
    text = "123 Main St, Sonoma, CA 95476-1234"
    assert je.find_zip_addresses(text) == [("Sonoma", "CA", "95476")]


def test_find_zip_addresses_returns_multiple_real_matches():
    text = "Main office: 1 Fiscal Dr, Santa Rosa, CA 95403. Branch: 123 Elm St, Napa, CA 94559."
    assert je.find_zip_addresses(text) == [
        ("Santa Rosa", "CA", "95403"),
        ("Napa", "CA", "94559"),
    ]


def test_find_zip_addresses_returns_empty_list_for_no_match():
    assert je.find_zip_addresses("No address here at all.") == []


def test_lookup_by_domain_resolves_a_confirmed_real_customer():
    known = je.lookup_by_domain("detroit-vod.cablecast.tv")
    assert known == je.KnownJurisdiction("Detroit", "city", "MI")


def test_lookup_by_domain_is_case_insensitive():
    assert je.lookup_by_domain("DETROIT-VOD.CABLECAST.TV").state == "MI"


def test_lookup_by_domain_returns_none_for_an_unconfirmed_domain():
    assert je.lookup_by_domain("some-random-city.example.com") is None


def test_resolve_state_prefers_a_confirmed_domain_over_an_ambiguous_name():
    # "Detroit" alone is unresolvable (real collision, see above) -- the
    # confirmed domain is what actually makes this resolve.
    assert je.resolve_state("Detroit", "city", netloc="detroit-vod.cablecast.tv") == "MI"


def test_resolve_state_falls_back_to_name_lookup_without_a_domain():
    assert je.resolve_state("Sonoma County", "county") == "CA"


def test_resolve_state_falls_back_to_zip_in_page_text_when_name_lookup_fails():
    # No confirmed domain, and the name itself ("Sonoma") isn't passed at
    # all here -- only a real address in the page text to go on, exactly
    # the "adapter found no state anywhere except a printed address" case
    # this module exists for.
    page_text = "Contact us: 575 Administration Dr, Santa Rosa, CA 95403"
    assert je.resolve_state(None, "county", page_text=page_text) == "CA"


def test_resolve_state_scopes_zip_lookup_to_the_caller_declared_type():
    # The real trap: a county-type caller must get the COUNTY crosswalk's
    # answer from a ZIP-in-text, not silently borrow the place crosswalk's
    # answer just because it's also a valid real place. Both answers give
    # the same real state here (CA), but the underlying lookup called
    # must be the county one -- verified indirectly via the "county" type
    # correctly still resolving at all for an address whose city portion
    # doesn't share Sonoma County's own name.
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    state = je.resolve_state("Sonoma", "county", page_text=page_text)
    assert state == "CA"


def test_resolve_state_returns_none_when_nothing_resolves():
    assert je.resolve_state("Not A Real Place Zzyzx", "city") is None
    assert je.resolve_state(None, "city") is None


def test_enrich_jurisdiction_text_appends_state_for_an_unambiguous_city():
    assert je.enrich_jurisdiction_text("City of Napa") == "City of Napa, CA"


def test_enrich_jurisdiction_text_detects_county_type_from_the_text_itself():
    assert je.enrich_jurisdiction_text("Sonoma County") == "Sonoma County, CA"


def test_enrich_jurisdiction_text_uses_a_confirmed_domain():
    assert je.enrich_jurisdiction_text("Detroit", netloc="detroit-vod.cablecast.tv") == "Detroit, MI"


def test_enrich_jurisdiction_text_falls_back_to_zip_in_page_text():
    page_text = "Board of Supervisors, 575 Administration Dr, Santa Rosa, CA 95403"
    assert je.enrich_jurisdiction_text("Sonoma County", page_text=page_text) == "Sonoma County, CA"


def test_enrich_jurisdiction_text_leaves_ambiguous_names_unchanged():
    assert je.enrich_jurisdiction_text("City of Alexandria") == "City of Alexandria"


def test_enrich_jurisdiction_text_skips_falsy_values():
    assert je.enrich_jurisdiction_text(None) is None
    assert je.enrich_jurisdiction_text("") == ""


def test_enrich_jurisdiction_text_skips_a_value_that_already_has_a_comma():
    assert je.enrich_jurisdiction_text("League City, TX") == "League City, TX"


def test_enrich_jurisdiction_text_skips_a_callers_placeholder():
    assert je.enrich_jurisdiction_text("Unknown Jurisdiction", placeholder="Unknown Jurisdiction") == "Unknown Jurisdiction"
