"""baseline schema

Revision ID: ee8f7ff76fb3
Revises: 
Create Date: 2026-08-10 08:13:48.317608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8f7ff76fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_url', sa.Text(), nullable=False),
    sa.Column('input_url_normalized', sa.String(length=2048), nullable=False),
    sa.Column('input_platform', sa.String(length=50), nullable=False),
    sa.Column('resolved_platform', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('video_found', sa.Boolean(), nullable=False),
    sa.Column('video_format', sa.String(length=10), nullable=True),
    sa.Column('transcript_found', sa.Boolean(), nullable=False),
    sa.Column('transcript_language', sa.String(length=10), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('video_warnings', sa.JSON(), nullable=True),
    sa.Column('transcript_warnings', sa.JSON(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('resolved_payload', sa.JSON(), nullable=True),
    sa.Column('resolve_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('archive_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_push_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_resolutions_external_id'), 'meeting_resolutions', ['external_id'], unique=False)
    op.create_index(op.f('ix_meeting_resolutions_input_platform'), 'meeting_resolutions', ['input_platform'], unique=False)
    op.create_index(op.f('ix_meeting_resolutions_input_url_normalized'), 'meeting_resolutions', ['input_url_normalized'], unique=False)
    op.create_index(op.f('ix_meeting_resolutions_status'), 'meeting_resolutions', ['status'], unique=False)
    op.create_table('problem_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_reports')
    op.drop_index(op.f('ix_meeting_resolutions_status'), table_name='meeting_resolutions')
    op.drop_index(op.f('ix_meeting_resolutions_input_url_normalized'), table_name='meeting_resolutions')
    op.drop_index(op.f('ix_meeting_resolutions_input_platform'), table_name='meeting_resolutions')
    op.drop_index(op.f('ix_meeting_resolutions_external_id'), table_name='meeting_resolutions')
    op.drop_table('meeting_resolutions')
    # ### end Alembic commands ###
