"""add last_alerted_at to saved_items

Revision ID: a6556277a68d
Revises: 34f94d49a2ac
Create Date: 2026-08-13 01:33:55.917733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6556277a68d'
down_revision: Union[str, Sequence[str], None] = '34f94d49a2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_items', sa.Column('last_alerted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Hand-added, not from autogenerate: every saved_search row that
    # already exists gets last_alerted_at = created_at, so the alert
    # sweep (archive/search_alerts.py) treats "meetings archived since
    # this search was saved" as the starting point -- not NULL, which the
    # application code treats as "no cursor yet, alert on everything ever
    # archived" and would otherwise dump every pre-existing match on the
    # very first run for every saved search that predates this migration.
    # saved_meeting rows are untouched (column stays NULL, meaningless
    # for that item_type).
    op.execute(
        "UPDATE saved_items SET last_alerted_at = created_at WHERE item_type = 'saved_search'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_items', 'last_alerted_at')
    # ### end Alembic commands ###
