"""baseline schema

Revision ID: a8dc5aad7eff
Revises:
Create Date: 2026-08-09 00:22:11.439964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dc5aad7eff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url_normalized', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_format', sa.String(length=10), nullable=True),
    sa.Column('agenda_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_pages_external_id'), 'meeting_pages', ['external_id'], unique=False)
    op.create_index(op.f('ix_meeting_pages_platform'), 'meeting_pages', ['platform'], unique=False)
    op.create_index(op.f('ix_meeting_pages_slug'), 'meeting_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_meeting_pages_source_url_normalized'), 'meeting_pages', ['source_url_normalized'], unique=False)
    op.create_table('meeting_page_url_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_normalized', sa.String(length=2048), nullable=False),
    sa.Column('meeting_page_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_page_id'], ['meeting_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_page_url_aliases_meeting_page_id'), 'meeting_page_url_aliases', ['meeting_page_id'], unique=False)
    op.create_index(op.f('ix_meeting_page_url_aliases_url_normalized'), 'meeting_page_url_aliases', ['url_normalized'], unique=True)
    op.create_table('transcript_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_page_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('transcript_warnings', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_page_id'], ['meeting_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_versions_content_hash'), 'transcript_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_transcript_versions_meeting_page_id'), 'transcript_versions', ['meeting_page_id'], unique=False)
    op.create_table('transcription_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_page_id', sa.Integer(), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('confirmation_token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('media_kind', sa.String(length=10), nullable=False),
    sa.Column('probed_duration_seconds', sa.Float(), nullable=False),
    sa.Column('chunk_size_seconds', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks_completed', sa.Integer(), nullable=False),
    sa.Column('partial_segments', sa.JSON(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_chunk_failures', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('transcript_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_page_id'], ['meeting_pages.id'], ),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['transcript_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_jobs_confirmation_token'), 'transcription_jobs', ['confirmation_token'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_meeting_page_id'), 'transcription_jobs', ['meeting_page_id'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_status'), 'transcription_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcription_jobs_status'), table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_meeting_page_id'), table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_confirmation_token'), table_name='transcription_jobs')
    op.drop_table('transcription_jobs')
    op.drop_index(op.f('ix_transcript_versions_meeting_page_id'), table_name='transcript_versions')
    op.drop_index(op.f('ix_transcript_versions_content_hash'), table_name='transcript_versions')
    op.drop_table('transcript_versions')
    op.drop_index(op.f('ix_meeting_page_url_aliases_url_normalized'), table_name='meeting_page_url_aliases')
    op.drop_index(op.f('ix_meeting_page_url_aliases_meeting_page_id'), table_name='meeting_page_url_aliases')
    op.drop_table('meeting_page_url_aliases')
    op.drop_index(op.f('ix_meeting_pages_source_url_normalized'), table_name='meeting_pages')
    op.drop_index(op.f('ix_meeting_pages_slug'), table_name='meeting_pages')
    op.drop_index(op.f('ix_meeting_pages_platform'), table_name='meeting_pages')
    op.drop_index(op.f('ix_meeting_pages_external_id'), table_name='meeting_pages')
    op.drop_table('meeting_pages')
    # ### end Alembic commands ###
