"""add priority to transcription_jobs

Revision ID: 8e7cf3b20f86
Revises: a8dc5aad7eff
Create Date: 2026-08-09 00:28:51.779075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e7cf3b20f86"
down_revision: Union[str, Sequence[str], None] = "a8dc5aad7eff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription_jobs",
        sa.Column("priority", sa.Integer(), server_default="10", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription_jobs", "priority")
    # ### end Alembic commands ###
