"""add meeting_highlights and search_queries

Revision ID: 1864f9d7702e
Revises: f6a7b8c9d0e1
Create Date: 2026-08-23 12:36:55.348354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1864f9d7702e"
down_revision: Union[str, Sequence[str], None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("jurisdiction", sa.String(length=200), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_queries_created_at"),
        "search_queries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_search_queries_keyword"), "search_queries", ["keyword"], unique=False
    )
    op.create_table(
        "meeting_highlights",
        sa.Column("meeting_page_id", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("topic_moments", sa.JSON(), nullable=False),
        sa.Column("topics_version", sa.Integer(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_page_id"], ["meeting_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("meeting_page_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_highlights")
    op.drop_index(op.f("ix_search_queries_keyword"), table_name="search_queries")
    op.drop_index(op.f("ix_search_queries_created_at"), table_name="search_queries")
    op.drop_table("search_queries")
    # ### end Alembic commands ###
