"""add video_warnings and agenda_link to meeting_pages

Revision ID: 76a4a2820a2b
Revises: 8e7cf3b20f86
Create Date: 2026-08-10 08:53:48.878302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76a4a2820a2b"
down_revision: Union[str, Sequence[str], None] = "8e7cf3b20f86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_pages", sa.Column("video_warnings", sa.JSON(), nullable=True)
    )
    op.add_column("meeting_pages", sa.Column("agenda_link", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_pages", "agenda_link")
    op.drop_column("meeting_pages", "video_warnings")
    # ### end Alembic commands ###
