"""Coop WebTV (webtv.coop) -- council video for Montreal-area governments.

One website, one channel per customer: `/channel/<slug>/<number>`. The
channel number is the tenant (see `app/utils/tenant_key.py`, `webtv.coop`).
Seven channels are governments (Beaconsfield 1, Baie-D'Urfe 3,
Pointe-Claire 4, Montreal-Est 5, Saint-Laurent 6, Sud-Ouest 7,
Sainte-Anne-de-Bellevue 18); their pins live in `tenant_overrides.csv`.

Everything below was read from real pages fetched 2026-10-07 (Pointe-Claire,
channel 4; fixtures in `tests/fixtures/webtv_coop/`), never assumed:

* Two video-page address shapes, both serving the same page:
  `/channel/video/<title-slug>/<32-hex key>/<channel number>` and
  `/video/<title-slug>/<32-hex key>`. The key is the media id.
* The page carries the HLS address in its player options
  (`"sources":[{"src":"https://<id>.streamlock.net/vod/smil:<key>_<n>.smil/
  playlist.m3u8?<number>"}]`, a Wowza server), the length as
  `videoDuration` (seconds), and, when captions exist, a
  `<track src="/webPlayerSubtitles/subtitleFile/key/<key>/filename/
  <lang>_subtitles.vtt" srclang="<lang>">` element per caption file.
* The number after `playlist.m3u8?` is the time the page was rendered, not
  an expiring token: two pages fetched 4 seconds apart showed values 4
  apart, and the same stream answered the same with that value, with a
  different one, and with none. We keep the address exactly as the page
  gives it.
* The stream answers `Access-Control-Allow-Origin: *`, so the reader's
  browser can play it with hls.js (`video_format="m3u8"`). ffprobe reads it
  with `media_probe.realistic_headers()` and without (checked 2026-10-07).
* Only the channel address names its channel. The site-wide page
  `/video/<slug>/<key>` does not: its `/channel/` links are site menu items
  (channels 12 and 13 on a channel-4 video), so `video_channel` stays empty
  for it and the video is unpinned.
* The title starts with the meeting date (`2026-10-06 Conseil de la Ville
  de Pointe-Claire`). No date is returned when the title does not start
  with one.
* Captions are machine-made (`WEBVTT - generated by WEBTV.COOP`) and can mix
  French and English inside one file labelled `fr` (Pointe-Claire
  2026-10-06). We do not correct them. About a third of Pointe-Claire's
  videos have no caption file: those resolve with no segments and a plain
  warning (Tier 3, our own transcription), they do not fail.

Which caption file when a video has more than one: the first one the page
lists becomes the transcript, and every other file is kept in
`alternate_transcripts`, so none is dropped. The page gives no way to tell
the spoken language from a translation (no live example with two files was
checked, only the single-file ones), so we follow the order webtv.coop's
own player shows and do not rank languages ourselves.

Politeness: `robots.txt` blocks only `/api/` and dev files. Requests go out
one at a time with an honest User-Agent, and a 429 stops the resolve at
once with a plain warning.
"""

import asyncio
import html as html_lib
import json
import logging
import re
from typing import List, Optional, Tuple
from urllib.parse import urljoin, urlparse

import aiohttp

from .base import AssetFinder
from .models import AlternateTranscript, ResolvedMeeting, TranscriptSegment
from ..utils.vtt_parser import decode_vtt_bytes, is_likely_garbled, parse_vtt

logger = logging.getLogger("rtr_deeplink.webtv_coop")

WEBTV_HOST = "webtv.coop"

# `/channel/video/<slug>/<key>/<n>` and `/video/<slug>/<key>`.
_VIDEO_PATH_RE = re.compile(
    r"^/(?:channel/video/[^/]+/(?P<key>[0-9a-f]{32})/(?P<channel>\d+)"
    r"|video/[^/]+/(?P<key2>[0-9a-f]{32}))/?$",
    re.IGNORECASE,
)
_CHANNEL_PATH_RE = re.compile(r"^/channel/(?!video/)[^/]+/(?P<channel>\d+)/?$")

_HLS_RE = re.compile(r'"sources":\[\{"src":"(?P<src>[^"]+)"')
_DURATION_RE = re.compile(r'"videoDuration":(?P<seconds>\d+)')
_TRACK_RE = re.compile(r"<track\b[^>]*>", re.IGNORECASE)
_TRACK_SRC_RE = re.compile(r'\bsrc="([^"]*webPlayerSubtitles[^"]*)"')
_TRACK_LANG_RE = re.compile(r'\bsrclang="([^"]*)"')
_H1_RE = re.compile(r'<h1 class="no-indent[^"]*">(?P<title>.*?)</h1>', re.S)
_TITLE_TAG_RE = re.compile(r"<title>(?P<title>.*?)</title>", re.S)
_TITLE_SUFFIX_RE = re.compile(
    r"(?:\s+-\s+(?:Cha[îi]nes|M[ée]dia))?\s+-\s+WEBTV\.COOP\s*$"
)
_DATE_RE = re.compile(r"^\s*(\d{4}-\d{2}-\d{2})")

# Seconds to wait between two requests to webtv.coop (one at a time).
PAUSE_BETWEEN_REQUESTS_SECONDS = 3.0

_USER_AGENT = "RedTapeRecordings/1.0 (+https://redtaperecordings.com)"


class WebtvRateLimited(Exception):
    """webtv.coop answered 429. Stop; do not retry."""


def is_webtv_coop_url(url: str) -> bool:
    host = (urlparse(url).hostname or "").lower()
    return host in (WEBTV_HOST, f"www.{WEBTV_HOST}")


def media_key_from_url(url: str) -> Optional[str]:
    """The 32-hex media key from either video-page shape, else None."""
    match = _VIDEO_PATH_RE.match(urlparse(url).path)
    if not match:
        return None
    return (match.group("key") or match.group("key2")).lower()


def channel_from_url(url: str) -> Optional[str]:
    """The channel number when the address carries one (a channel page or a
    `/channel/video/...` page), else None -- the `/video/<slug>/<key>`
    shape does not name its channel."""
    path = urlparse(url).path
    match = _VIDEO_PATH_RE.match(path) or _CHANNEL_PATH_RE.match(path)
    return match.group("channel") if match and match.group("channel") else None


def _strip_tags(text: str) -> str:
    return html_lib.unescape(re.sub(r"<[^>]+>", "", text)).strip()


class WebtvCoopAssetFinder(AssetFinder):
    platform_name = "webtv_coop"

    async def resolve(self, url: str) -> ResolvedMeeting:
        key = media_key_from_url(url)
        if not key:
            return ResolvedMeeting(
                platform=self.platform_name,
                source_url=url,
                video_warnings=[
                    "This is a webtv.coop page, but not a single video. Open the "
                    "video itself and paste that link."
                ],
            )

        try:
            async with aiohttp.ClientSession(
                headers={"User-Agent": _USER_AGENT}
            ) as session:
                html = await self._fetch_text(session, url)
                if html is None:
                    return ResolvedMeeting(
                        platform=self.platform_name,
                        source_url=url,
                        external_id=f"webtv_coop:{key}",
                        video_warnings=["Could not load this webtv.coop video page."],
                    )
                tracks = self._tracks(html)
                loaded: List[Tuple[str, List[dict]]] = []
                for lang, track_url in tracks:
                    await asyncio.sleep(PAUSE_BETWEEN_REQUESTS_SECONDS)
                    cues = await self._fetch_vtt(session, track_url)
                    if cues:
                        loaded.append((lang, cues))
        except WebtvRateLimited:
            return ResolvedMeeting(
                platform=self.platform_name,
                source_url=url,
                external_id=f"webtv_coop:{key}",
                video_warnings=[
                    "webtv.coop asked us to slow down (HTTP 429), so we stopped. "
                    "Try again later."
                ],
            )

        # Only the address names the channel. The site-wide `/video/...` page
        # does not: its `/channel/...` links are site navigation (checked
        # 2026-10-07, they pointed at channels 12 and 13 on a channel-4
        # video), so reading them would pin the wrong government.
        channel = channel_from_url(url)

        video_url = self._hls_url(html)
        duration = self._duration(html)
        title = self._title(html)

        resolved = ResolvedMeeting(
            platform=self.platform_name,
            source_url=url,
            external_id=f"webtv_coop:{key}",
            title=title,
            date=self._date(title),
            video_channel=f"webtv_coop:{channel}" if channel else None,
            video_url=video_url,
            video_format="m3u8" if video_url else None,
            video_duration_seconds=duration,
        )
        if not video_url:
            resolved.video_warnings = [
                "We found this webtv.coop page but not a playable video stream on it."
            ]

        if loaded:
            primary_lang, primary_cues = loaded[0]
            resolved.segments = [TranscriptSegment(**c) for c in primary_cues]
            resolved.transcript_language = primary_lang or None
            resolved.alternate_transcripts = [
                AlternateTranscript(
                    language=lang or None,
                    segments=[TranscriptSegment(**c) for c in cues],
                )
                for lang, cues in loaded[1:]
            ]
            if is_likely_garbled(primary_cues, lang=primary_lang or None):
                resolved.transcript_warnings.append(
                    "This transcript looks garbled at the source (not a parsing "
                    "bug on our end) -- treat it as approximate."
                )
        else:
            resolved.transcript_warnings.append("No captions found for this video.")
        return resolved

    @staticmethod
    def _hls_url(html: str) -> Optional[str]:
        match = _HLS_RE.search(html)
        if not match:
            return None
        try:
            return json.loads(f'"{match.group("src")}"')
        except json.JSONDecodeError:
            return None

    @staticmethod
    def _duration(html: str) -> Optional[float]:
        match = _DURATION_RE.search(html)
        if not match:
            return None
        seconds = int(match.group("seconds"))
        return float(seconds) if seconds > 0 else None

    @staticmethod
    def _title(html: str) -> Optional[str]:
        match = _H1_RE.search(html)
        if match:
            return _strip_tags(match.group("title")) or None
        match = _TITLE_TAG_RE.search(html)
        if match:
            return _TITLE_SUFFIX_RE.sub("", _strip_tags(match.group("title"))) or None
        return None

    @staticmethod
    def _date(title: Optional[str]) -> Optional[str]:
        match = _DATE_RE.match(title or "")
        return match.group(1) if match else None

    @staticmethod
    def _tracks(html: str) -> List[Tuple[str, str]]:
        """`(language, absolute caption URL)` per caption `<track>`, in the
        order the page lists them."""
        out = []
        for tag in _TRACK_RE.findall(html):
            src = _TRACK_SRC_RE.search(tag)
            if not src:
                continue
            lang = _TRACK_LANG_RE.search(tag)
            out.append(
                (
                    lang.group(1) if lang else "",
                    urljoin(f"https://{WEBTV_HOST}/", src.group(1)),
                )
            )
        return out

    @staticmethod
    async def _fetch_text(session: aiohttp.ClientSession, url: str) -> Optional[str]:
        try:
            async with session.get(
                url, allow_redirects=True, timeout=aiohttp.ClientTimeout(total=30)
            ) as response:
                if response.status == 429:
                    raise WebtvRateLimited()
                if response.status != 200:
                    logger.warning(
                        "webtv.coop page HTTP %s for %s", response.status, url
                    )
                    return None
                return await response.text()
        except WebtvRateLimited:
            raise
        except Exception:
            logger.warning("webtv.coop page fetch failed for %s", url, exc_info=True)
            return None

    @staticmethod
    async def _fetch_vtt(session: aiohttp.ClientSession, vtt_url: str):
        try:
            async with session.get(
                vtt_url, timeout=aiohttp.ClientTimeout(total=30)
            ) as response:
                if response.status == 429:
                    raise WebtvRateLimited()
                if response.status != 200:
                    logger.warning(
                        "webtv.coop VTT HTTP %s for %s", response.status, vtt_url
                    )
                    return None
                raw = await response.read()
        except WebtvRateLimited:
            raise
        except Exception:
            logger.warning("webtv.coop VTT fetch failed for %s", vtt_url, exc_info=True)
            return None
        return parse_vtt(decode_vtt_bytes(raw)) or None
