"""WO-347 (2026-09-13): rerun the 281 rows WO-338's own rerun left as tier
4 "meeting, no video" on the five platforms that gained a listing walker
either before or shortly after WO-338 ran (civicplus, escribe,
civicclerk, iqm2, townhallstreams).

## Why these 281 and not the rest of `wo338_verify.csv`

WO-338 (PR #1131) reran 2,825 mislabelled governments through
`verify_hub()` and produced `research/wo338_verify.csv`, 623 rows (one
per confirmed platform). WO-345 (= WO-338b, PR #1134) already rerun the
108 rows whose `tier` column was BLANK (`meeting_found=False`, the
"walk came back empty" bucket) on those same six walker platforms
(including cablecast, which had zero rows in that particular bucket).
This WO covers the population WO-345 explicitly did not touch: the 281
rows whose `tier` is `'4'` -- `verify_hub()` DID confirm a real meeting
listing/page last time (`meeting_found=True`), just no video on it. A
tier-4 verdict was never necessarily final either: `passive_verify.py`'s
own listing walkers (CivicPlus WO-341, CivicClerk WO-342, eScribe
WO-343, iQM2/Town Hall Streams WO-344) keep improving, and a walker that
previously stopped at the first page of a paginated listing, or missed a
video link buried past the agenda text, can turn up a real video on a
rerun against the exact same hub URL with no site change at all.

Population (built once, on disk, not re-derived by this script -- see
`research/wo347_population.csv`, generated by a one-off filter kept for
audit): every row of `research/wo338_verify.csv` with `tier == '4'` and
`platform_hint` in {civicplus, escribe, civicclerk, iqm2,
townhallstreams} (cablecast excluded -- the task scope named five
platforms, not six; cablecast's WO-344 template gap was about a
different, non-tier-4 population) AND whose `gov_id` does not appear in
`research/wo345_report.csv` (confirmed zero overlap -- WO-345's own
population was the blank-tier bucket, disjoint from tier 4 by
construction). Counts: civicplus 222, escribe 33, civicclerk 19, iqm2 4,
townhallstreams 3 -- 281 total, matching the brief exactly.

Re-verifies from the SAME `hub_url` WO-338 already confirmed (no fresh
recon) via `app.platforms.passive_verify.verify_hub()`, current `main`.
Writes `research/wo347_rerun_verify.csv` (resumable: a domain already
present is skipped), same column shape as `wo345_verify.csv`. Never
fetches a youtube.com/youtu.be URL (verify_hub's own
`_youtube_resolve_guard()`). Never downloads a media file.

Usage (from the rtr-deeplink repo root, shared venv):
    DATABASE_URL="sqlite+aiosqlite:////tmp/wo347_verify_scratch.db" \\
        .venv/bin/python scripts/wo347_verify.py --limit 50
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import os
import sys
import time
from pathlib import Path

import certifi

os.environ.setdefault("SSL_CERT_FILE", certifi.where())

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.platforms import register_all_finders  # noqa: E402
from app.platforms.passive_verify import verify_hub  # noqa: E402

register_all_finders()

RESEARCH_DIR = Path.home() / "Documents" / "rtr-business" / "research"
WO338_VERIFY_CSV = RESEARCH_DIR / "wo338_verify.csv"
WO345_REPORT_CSV = RESEARCH_DIR / "wo345_report.csv"
VERIFY_CSV = RESEARCH_DIR / "wo347_rerun_verify.csv"

TARGET_PLATFORMS = {
    "civicplus",
    "escribe",
    "civicclerk",
    "iqm2",
    "townhallstreams",
}

FIELDNAMES = [
    "domain",
    "gov_id",
    "name",
    "state",
    "hub_url",
    "platform_hint",
    "prior_verdict",
    "prior_evidence",
    "verdict",
    "tier",
    "meeting_found",
    "video_found",
    "captions_found",
    "meeting_url",
    "resolved_platform",
    "evidence",
    "candidates_checked",
    "ranking_fix_applied",
    "error",
]


def log(msg: str) -> None:
    print(msg, flush=True)


def load_population() -> list[dict]:
    """281 rows: WO-338's tier-4 ("meeting, no video") verdicts on the
    five platforms that have a listing walker, minus WO-345's own
    (disjoint, blank-tier) population."""
    already = set()
    if WO345_REPORT_CSV.exists():
        with open(WO345_REPORT_CSV, newline="", encoding="utf-8") as f:
            already = {row["gov_id"] for row in csv.DictReader(f)}

    pop = []
    with open(WO338_VERIFY_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if (
                row.get("tier", "") == "4"
                and row.get("platform_hint") in TARGET_PLATFORMS
                and row.get("gov_id") not in already
            ):
                pop.append(row)
    return pop


def load_done_domains() -> set:
    done = set()
    if VERIFY_CSV.exists():
        with open(VERIFY_CSV, newline="", encoding="utf-8") as f:
            done = {row["domain"] for row in csv.DictReader(f)}
    return done


async def verify_one(row: dict) -> dict:
    domain = row["domain"]
    hub_url = row["hub_url"]
    platform_hint = row.get("platform_hint") or None
    out = {
        "domain": domain,
        "gov_id": row.get("gov_id", ""),
        "name": row.get("name", ""),
        "state": row.get("state", ""),
        "hub_url": hub_url,
        "platform_hint": platform_hint or "",
        "prior_verdict": row.get("verdict", ""),
        "prior_evidence": (row.get("evidence", "") or "")[:300],
        "verdict": "",
        "tier": "",
        "meeting_found": False,
        "video_found": False,
        "captions_found": False,
        "meeting_url": "",
        "resolved_platform": "",
        "evidence": "",
        "candidates_checked": 0,
        "ranking_fix_applied": False,
        "error": "",
    }
    try:
        result = await verify_hub(hub_url, platform_hint=platform_hint)
    except Exception as e:  # noqa: BLE001
        out["error"] = f"{type(e).__name__}: {str(e)[:300]}"
        out["verdict"] = "exception"
        return out

    out["verdict"] = result.verdict
    out["tier"] = result.tier if result.tier is not None else ""
    out["meeting_found"] = result.meeting_found
    out["video_found"] = result.video_found
    out["captions_found"] = result.captions_found
    out["meeting_url"] = result.meeting_url or ""
    out["resolved_platform"] = result.platform or ""
    out["evidence"] = (result.evidence or "")[:500]
    out["candidates_checked"] = result.candidates_checked
    out["ranking_fix_applied"] = result.ranking_fix_applied
    return out


async def main_async(limit: int, concurrency: int) -> None:
    population = load_population()
    done = load_done_domains()
    remaining = [row for row in population if row["domain"] not in done]
    log(
        f"{len(population)} governments in the tier-4 walker rerun, "
        f"{len(done)} already re-verified, {len(remaining)} remaining"
    )
    to_process = remaining[:limit] if limit else remaining
    log(f"re-verifying {len(to_process)} at concurrency={concurrency}")

    write_header = not VERIFY_CSV.exists()
    sem = asyncio.Semaphore(concurrency)
    lock = asyncio.Lock()
    completed = 0
    start = time.monotonic()

    with open(VERIFY_CSV, "a", newline="", encoding="utf-8") as out:
        writer = csv.DictWriter(out, fieldnames=FIELDNAMES)
        if write_header:
            writer.writeheader()
            out.flush()

        async def worker(row):
            nonlocal completed
            async with sem:
                result = await verify_one(row)
            async with lock:
                writer.writerow(result)
                out.flush()
                completed += 1
                if completed % 10 == 0 or completed == len(to_process):
                    elapsed = time.monotonic() - start
                    rate = completed / elapsed * 60 if elapsed > 0 else 0
                    log(
                        f"[{completed}/{len(to_process)}] elapsed={elapsed:.0f}s "
                        f"rate={rate:.1f}/min last={row['domain']}"
                    )

        await asyncio.gather(*(worker(row) for row in to_process))

    log(f"chunk done: {len(to_process)} re-verified")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--concurrency", type=int, default=8)
    args = parser.parse_args()
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    asyncio.run(main_async(args.limit, args.concurrency))


if __name__ == "__main__":
    main()
